import React, {useEffect, useRef, useState} from 'react';
import {array,dayLabel,ErrorNotice,PageHeading,personalApi,StatusNotice,today} from './personalApi';

export default function Assistant() {
  const [day,setDay] = useState(today()), [days,setDays] = useState(14), [includeMedical,setIncludeMedical] = useState(false), [question,setQuestion] = useState(''), [manual,setManual] = useState('');
  const [context,setContext] = useState(null), [history,setHistory] = useState([]), [result,setResult] = useState(null), [loading,setLoading] = useState(true), [busy,setBusy] = useState(false), [error,setError] = useState(''), [message,setMessage] = useState('');
  const sequence = useRef(0);
  const [refresh,setRefresh] = useState(0);
  async function loadHistory() {const response=await personalApi('assistant/history');setHistory(array(response.messages || response.history || response.entries || response.reports || response).slice().reverse());}
  useEffect(()=>{const version=++sequence.current;setLoading(true);setContext(null);setError('');setResult(null);setManual('');setMessage('');Promise.all([personalApi(`assistant/context?day=${encodeURIComponent(day)}&days=${days}&include_medical=${includeMedical}`),personalApi('assistant/history')]).then(([value,reports])=>{if(version!==sequence.current)return;setContext(value);setHistory(array(reports.messages || reports.history || reports.entries || reports.reports || reports).slice().reverse());}).catch(e=>{if(version===sequence.current)setError(e.message);}).finally(()=>{if(version===sequence.current)setLoading(false);});return()=>{sequence.current++;};},[day,days,includeMedical,refresh]);
  async function send(imported=false) {setBusy(true);setError('');setMessage('');try{const value=await personalApi('assistant',{question:question.trim(),day,days,include_medical:includeMedical,fingerprint:context?.fingerprint,...(imported?{manual_response:manual.trim()}:{})});setResult(value);setMessage(imported?'Resposta importada e identificada no histórico.':'Análise salva no histórico.');setManual('');await loadHistory();}catch(e){setError(e.message);}finally{setBusy(false);}}
  const prompt = (question ? 'PERGUNTA: '+question+'\n\n' : '') + (context?.prompt || (context ? `${question ? 'PERGUNTA: '+question+'\n\n':''}CONTEXTO:\n${JSON.stringify(context.context || context,null,2)}` : ''));
  async function copy() {try{await navigator.clipboard.writeText(prompt);setMessage('Contexto copiado.');}catch{setError('Selecione o texto do contexto e copie manualmente.');}}
  const records = result ? [result,...history.filter(row=>!result.id || row.id!==result.id)] : history;
  return <><PageHeading kicker="SUA HISTÓRIA / PERGUNTAS / INTELIGÊNCIA" title="Converse com o seu contexto.">Use o período que faz sentido e confira os registros enviados antes da análise.</PageHeading><ErrorNotice error={error}/><StatusNotice message={message}/><section className="panel"><div className="filters"><label>Até o dia<input type="date" value={day} disabled={busy} onChange={e=>setDay(e.target.value)}/></label><label>Período<select value={days} disabled={busy} onChange={e=>setDays(Number(e.target.value))}><option value="7">7 dias</option><option value="14">14 dias</option><option value="30">30 dias</option></select></label><button disabled={busy || loading} onClick={()=>setRefresh(v=>v+1)}>Atualizar contexto</button></div><label className="checkbox-label medical-scope"><input type="checkbox" disabled={busy} checked={includeMedical} onChange={e=>setIncludeMedical(e.target.checked)}/>Incluir as referências médicas registradas nesta análise</label><p className="small muted">Ao gerar, a pergunta e o contexto escolhido são enviados ao provedor de IA. O contexto se encerra na data selecionada.</p>{loading&&<p className="muted" role="status">Reunindo o contexto…</p>}<label className="question-label">O que você quer entender?<textarea rows="4" maxLength="5000" value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ex.: minha alimentação e minha carga de treino estão coerentes com o meu objetivo?"/></label><div className="suggestion-buttons">{['O que mudou neste período?','Tenho dados suficientes para revisar meu objetivo?','Como estão alimentação, carga e recuperação?'].map(text=><button key={text} disabled={busy} onClick={()=>setQuestion(text)}>{text}</button>)}</div><div className="report-actions"><button className="primary" disabled={busy || loading || !context || question.trim().length<3 || context.configured===false} onClick={()=>send()}>{busy?'Preparando resposta…':'Perguntar à IA'}</button><button disabled={!context || busy} onClick={copy}>Copiar contexto</button></div>{context?.configured===false&&<p className="notice">A geração automática não está configurada. Você pode usar o contexto em outra IA e importar sua resposta.</p>}<details className="method"><summary>Ver contexto e dados enviados</summary><textarea className="daily-textarea" readOnly aria-label="Contexto do assistente" rows="12" value={prompt}/></details><details className="method"><summary>Importar resposta de outra IA</summary><p>Use o contexto e a pergunta deste período. A resposta será identificada como importada.</p><textarea className="daily-textarea" aria-label="Resposta de outra IA" rows="5" maxLength="30000" value={manual} onChange={e=>setManual(e.target.value)} placeholder="Cole a resposta aqui…"/><button disabled={busy || !context || question.trim().length<3 || manual.trim().length<20} onClick={()=>send(true)}>Salvar resposta importada</button></details></section>
    <section className="panel"><div className="panel-heading"><div><h2>Conversas e análises</h2><p>Respostas datadas, com o contexto utilizado para interpretá-las.</p></div></div>{records.length ? records.slice(0,20).map((row,index)=><article className="assistant-message" key={row.id || index}><div className="assistant-meta"><span>{dayLabel(row.day || row.date || row.created_at || row.generated_at)}</span><span>{row.model || (row.source==='manual'?'Resposta importada':'Análise por IA')}</span>{row.stale&&<span className="tag stale">Dados alterados</span>}</div><h3>{row.question || 'Análise do período'}</h3><div className="daily-report">{row.answer || row.response || row.text || row.report?.text || 'Resposta indisponível.'}</div>{array(row.limitations).length>0&&<div className="notice">{row.limitations.join(' ')}</div>}<details className="method"><summary>Consultar o contexto desta resposta</summary><pre className="context-preview">{row.prompt || JSON.stringify(row.context || {},null,2)}</pre></details></article>) : <p className="empty">Sua primeira pergunta inicia este histórico.</p>}</section>
  </>;
}
