import React, {useEffect, useState} from 'react';
import {array,dayLabel,ErrorNotice,PageHeading,personalApi,StatusNotice,today} from './personalApi';

export default function Documents() {
  const [documents,setDocuments] = useState([]), [file,setFile] = useState(null), [label,setLabel] = useState(''), [date,setDate] = useState(today()), [draft,setDraft] = useState(null), [busy,setBusy] = useState(false), [loading,setLoading] = useState(true), [error,setError] = useState(''), [message,setMessage] = useState(''), [consent,setConsent] = useState({});
  async function load(){setLoading(true);try{const value=await personalApi('documents');setDocuments(array(value.documents));}catch(e){setError(e.message);}finally{setLoading(false);}}
  useEffect(()=>{load();},[]);
  async function run(action,notice){setBusy(true);setError('');setMessage('');try{await action();await load();if(notice)setMessage(notice);}catch(e){setError(e.message);}finally{setBusy(false);}}
  async function upload(event){event.preventDefault();if(!file)return;await run(async()=>{if(file.size>12*1024*1024)throw new Error('Escolha um documento de até 12 MB.');const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=16384)binary+=String.fromCharCode(...bytes.subarray(i,i+16384));await personalApi('documents',{filename:file.name,content:btoa(binary),label:label.trim() || file.name,date});setFile(null);setLabel('');},'Documento privado salvo. Resultados só serão incorporados após revisão.');}
  function edit(index,key,value){setDraft(v=>({...v,observations:v.observations.map((row,i)=>i===index?{...row,[key]:value}:row)}));}
  return <><PageHeading kicker="DOCUMENTOS / RESULTADOS / REVISÃO" title="Guarde o documento. Confira a interpretação.">Exames e referências permanecem privados e só se tornam observações estruturadas depois da sua revisão.</PageHeading><ErrorNotice error={error}/><StatusNotice message={message}/><section className="panel"><h2>Adicionar documento</h2><form className="personal-form" onSubmit={upload}><div className="form-grid"><label>Documento (até 12 MB)<input type="file" accept=".pdf,.txt,.png,.jpg,.jpeg,.webp" disabled={busy} onChange={e=>setFile(e.target.files?.[0] || null)}/></label><label>Identificação<input value={label} maxLength="300" onChange={e=>setLabel(e.target.value)} placeholder="Ex.: avaliação, exame, orientação"/></label><label>Data de referência<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></div><button className="primary" disabled={busy || !file}>{busy?'Processando…':'Salvar documento'}</button></form></section>
    {draft&&<section className="panel"><div className="panel-heading"><div><h2>Revisar resultados extraídos</h2><p>{draft.notes || 'Compare os itens com o documento original antes de incorporar.'}</p></div><button disabled={busy} onClick={()=>setDraft(null)}>Fechar revisão</button></div><form onSubmit={event=>{event.preventDefault();run(async()=>{await personalApi(`documents/${encodeURIComponent(draft.document_id)}/review`,{observations:draft.observations});setDraft(null);},'Observações revisadas e incorporadas.');}}><div className="table-scroll"><table><thead><tr><th>Indicador</th><th>Valor</th><th>Unidade</th><th>Data</th><th>Página</th><th>Excluir</th></tr></thead><tbody>{array(draft.observations).map((row,index)=><tr key={index}><td><input aria-label={`Indicador ${index+1}`} value={row.name || ''} required onChange={e=>edit(index,'name',e.target.value)}/></td><td><input aria-label={`Valor ${index+1}`} value={row.value ?? ''} onChange={e=>edit(index,'value',e.target.value)}/></td><td><input aria-label={`Unidade ${index+1}`} value={row.unit || ''} onChange={e=>edit(index,'unit',e.target.value)}/></td><td><input aria-label={`Data ${index+1}`} type="date" value={row.date || ''} onChange={e=>edit(index,'date',e.target.value)}/></td><td><input aria-label={`Página ${index+1}`} type="number" min="1" value={row.page ?? ''} onChange={e=>edit(index,'page',e.target.value ? Number(e.target.value) : null)}/></td><td><button type="button" onClick={()=>setDraft(v=>({...v,observations:v.observations.filter((_,i)=>i!==index)}))}>Remover</button></td></tr>)}</tbody></table></div><div className="report-actions"><button type="button" onClick={()=>setDraft(v=>({...v,observations:[...v.observations,{name:'',value:'',unit:'',date,page:null}]}))}>Adicionar resultado</button><button className="primary" disabled={busy || !draft.observations.length}>Confirmar resultados revisados</button></div></form></section>}
    <section className="panel"><h2>Arquivo privado</h2>{loading&&<p className="muted" role="status">Consultando documentos…</p>}{documents.length?documents.map(document=><article className="document-card" key={document.id}><div className="proposal-heading"><h3>{document.label || document.filename}</h3><span className="tag">{document.reviewed?'Revisado':document.status==='extracted'?'Extração pendente de revisão':'Documento original'}</span></div><p className="small muted">{dayLabel(document.date)} · {document.filename}</p><div className="report-actions"><a className="button" href={`/api/documents/${encodeURIComponent(document.id)}/file`} target="_blank" rel="noreferrer">Abrir original</a><button disabled={busy} onClick={()=>setDraft({document_id:document.id,observations:array(document.observations).map(row=>({...row})),notes:'Digite ou revise os resultados consultando o documento original.'})}>Registrar resultados manualmente</button><button disabled={busy} onClick={()=>run(()=>personalApi(`documents/${encodeURIComponent(document.id)}/remove`,{}),'Documento removido.')}>Remover documento</button></div><details className="method"><summary>Extrair resultados com IA</summary><p>Esta opção envia o conteúdo extraído deste documento ao provedor de IA. A resposta fica pendente da sua revisão.</p><label className="checkbox-label"><input type="checkbox" checked={Boolean(consent[document.id])} onChange={e=>setConsent(v=>({...v,[document.id]:e.target.checked}))}/>Enviar este documento para extração com IA</label><button disabled={busy || !consent[document.id]} onClick={()=>run(async()=>{const result=await personalApi(`documents/${encodeURIComponent(document.id)}/extract`,{use_ai:true});setDraft({document_id:document.id,observations:array(result.draft?.observations).map(row=>({...row})),notes:result.draft?.notes});},'Extração preparada. Confira os valores antes de confirmar.')}>Extrair e revisar</button></details>{array(document.observations).length>0&&<details className="method"><summary>Resultados revisados</summary><div className="table-scroll"><table><thead><tr><th>Indicador</th><th>Resultado</th><th>Referência</th></tr></thead><tbody>{document.observations.map((row,index)=><tr key={index}><td>{row.name}</td><td>{row.value} {row.unit}</td><td>{dayLabel(row.date)}{row.page?` · pág. ${row.page}`:''}</td></tr>)}</tbody></table></div></details>}</article>):!loading&&<p className="empty">Nenhum documento adicional registrado.</p>}</section></>;
}
