import React, {useEffect, useRef, useState} from 'react';
import {array,dayLabel,ErrorNotice,format,optionalNumber,PageHeading,personalApi,StatusNotice,today} from './personalApi';

const nutrients = {kcal:'Calorias (kcal)',protein_g:'Proteína (g)',carbs_g:'Carboidratos (g)',fat_g:'Gorduras (g)'};
const meals = ['Café da manhã','Almoço','Lanche','Jantar','Ceia','Outro'];
const emptyItem = ()=>({name:'',kcal:null,protein_g:null,carbs_g:null,fat_g:null});
const blank = ()=>({id:crypto.randomUUID(),meal:'Lanche',text:'',analysis:null,image:null});
const clone = value=>JSON.parse(JSON.stringify(value));
function sum(items,key) {const known=array(items).filter(item=>item[key]!=null);return known.length?known.reduce((value,item)=>value+Number(item[key]),0):null;}
function totalLabel(diary,key) {if(!diary.entries.length)return diary.fasting_declared?'0':'Sem dado';const known=diary.entries.some(entry=>array(entry.analysis?.items).some(item=>item[key]!=null));return known?format(diary.totals[key],0):'Pendente';}

export default function FoodDiary() {
  const [day,setDay] = useState(today()), [diary,setDiary] = useState(null), [entry,setEntry] = useState(blank), [editing,setEditing] = useState(false), [manual,setManual] = useState(''), [prompt,setPrompt] = useState(''), [imageConsent,setImageConsent] = useState(false);
  const [recipes,setRecipes] = useState([]), [recipeTitle,setRecipeTitle] = useState(''), [servings,setServings] = useState(1), [busy,setBusy] = useState(false), [loading,setLoading] = useState(true), [error,setError] = useState(''), [message,setMessage] = useState(''), [fasting,setFasting] = useState(false);
  const [portions,setPortions] = useState({});
  const version = useRef(0);
  async function load(selectedDay=day) {const result=await personalApi('food/'+selectedDay);if(selectedDay===day){setDiary(result);setFasting(Boolean(result.fasting_declared));}return result;}
  async function loadLibrary() {const value=await personalApi('food-library');setRecipes(array(value.recipes));}
  useEffect(()=>{const request=++version.current;setLoading(true);setDiary(null);setEntry(blank());setEditing(false);setPrompt('');setManual('');setError('');setMessage('');setImageConsent(false);personalApi('food/'+day).then(value=>{if(request===version.current){setDiary(value);setFasting(Boolean(value.fasting_declared));}}).catch(e=>{if(request===version.current)setError(e.message);}).finally(()=>{if(request===version.current)setLoading(false);});return()=>{version.current++;};},[day]);
  useEffect(()=>{loadLibrary().catch(()=>{});},[]);
  async function run(action) {setBusy(true);setError('');setMessage('');try{return await action();}catch(e){setError(e.message);if(e.status===409 || /diário mudou/i.test(e.message))await load().catch(()=>{});return null;}finally{setBusy(false);}}
  function reset(){setEntry(blank());setEditing(false);setManual('');setPrompt('');setImageConsent(false);setRecipeTitle('');setServings(1);}
  function input(key,value){setEntry(previous=>({...previous,[key]:value,...(key==='text'?{analysis:null}:{})}));setPrompt('');}
  function editItem(index,key,value){setEntry(previous=>({...previous,analysis:{...previous.analysis,items:previous.analysis.items.map((item,i)=>i===index?{...item,[key]:key==='name'?value:optionalNumber(value)}:item)}}));}
  async function analyze(imported=false){await run(async()=>{const analysis=await personalApi(`food/${day}/analyze`,{text:entry.text || 'Estime os alimentos visíveis na foto, declarando porções e ingredientes incertos.',meal:entry.meal,...(imported?{analysis:JSON.parse(manual)}:{}),...(!imported && entry.image && imageConsent?{image:entry.image}:{})});setEntry(value=>({...value,analysis}));setMessage('Estimativa preparada. Revise os itens antes de salvar.');});}
  async function save(pending=false){await run(async()=>{const result=await personalApi(`food/${day}/save`,{...entry,text:entry.text.trim() || 'Refeição registrada por foto.',analysis:pending?null:entry.analysis,revision:diary.revision});setDiary(value=>({...value,...result}));setFasting(Boolean(result.fasting_declared));reset();setMessage(pending?'Refeição salva com estimativa pendente.':'Refeição salva. O total do dia foi atualizado.');});}
  async function imageSelected(file){setError('');setImageConsent(false);if(!file){setEntry(value=>({...value,image:null}));return;}if(!['image/jpeg','image/png','image/webp'].includes(file.type)){setError('Escolha uma foto JPEG, PNG ou WebP.');return;}if(file.size>6*1024*1024){setError('A foto deve ter até 6 MB.');return;}try{const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=16384)binary+=String.fromCharCode(...bytes.subarray(i,i+16384));setEntry(value=>({...value,image:`data:${file.type};base64,${btoa(binary)}`,analysis:null}));}catch{setError('Não foi possível ler a foto.');}}
  function edit(row,copy=false){setEntry({...clone(row),id:copy?crypto.randomUUID():row.id,image:null});setEditing(!copy);setPrompt('');setManual('');setMessage(copy?'Cópia preparada. Revise e salve como uma nova refeição.':'Refeição aberta para edição.');setImageConsent(false);window.scrollTo({top:0,behavior:'smooth'});}
  function useRecipe(recipe) {const selected=Number(portions[recipe.id] || 1),yielded=Number(recipe.servings || 1),factor=selected/yielded;const analysis=recipe.analysis?clone(recipe.analysis):null;if(analysis){analysis.items=analysis.items.map(item=>({...item,name:`${item.name} · ${selected} de ${yielded} porções`,...Object.fromEntries(Object.keys(nutrients).map(key=>[key,item[key]==null?null:Math.round(Number(item[key])*factor*10)/10]))}));analysis.notes=`${analysis.notes || ''}\nReceita escalada para ${selected} de ${yielded} porções. Revise as quantidades.`;}setEntry({...blank(),text:`${recipe.text}\nConsumi ${selected} de ${yielded} porções da receita.`,analysis});setEditing(false);setImageConsent(false);setPrompt('');setManual('');setMessage('Porção da receita preparada. Confira e salve a refeição.');window.scrollTo({top:0,behavior:'smooth'});}
  const pending = diary?.pending_count || 0;
  const analysis = entry.analysis;
  const canAnalyze = entry.text.trim().length>=3 || (entry.image && imageConsent);
  return <><PageHeading kicker="REFEIÇÕES / CALORIAS / CONTEXTO" title="Alimentação sem perder os detalhes.">Descreva, estime e revise. Registrar primeiro também funciona quando a IA não está disponível.</PageHeading><ErrorNotice error={error}/><StatusNotice message={message}/><div className="filters"><label>Dia<input type="date" value={day} disabled={busy} onChange={e=>setDay(e.target.value)}/></label><button disabled={busy || loading} onClick={()=>run(load)}>Atualizar o diário</button><span className={'tag '+(diary?.completeness==='complete'?'completed':'pending')}>{({empty:'Sem registros',partial:'Diário parcial',complete:'Dia declarado completo'})[diary?.completeness] || 'Consultando'}</span></div>{loading&&<p className="muted" role="status">Reunindo seu diário…</p>}
    {diary&&<><div className="metrics four">{Object.entries(nutrients).map(([key,label])=><div className="metric" key={key}><div className="eyebrow">{label}</div><div className="metric-value">{totalLabel(diary,key)}</div><p className="small muted">{diary.unknown_nutrients?.[key] ? `Subtotal conhecido · ${diary.unknown_nutrients[key]} refeição(ões) com valor pendente` : 'Total das refeições salvas'}</p></div>)}</div>{(!diary.complete_nutrition || pending>0)&&<div className="notice"><strong>{pending?`${pending} refeição(ões) com calorias pendentes`:'Diário em andamento'}</strong><p>O subtotal conhecido não representa a ingestão total quando a cobertura é parcial ou há calorias pendentes. Mesmo um dia declarado completo pode ter estimativas a revisar. Campos vazios permanecem desconhecidos e não contam como zero.</p></div>}
      <section className="panel"><div className="panel-heading"><div><h2>{editing?'Editar refeição':'Adicionar refeição'}</h2><p>{editing?'A correção mantém a mesma refeição e fica no histórico.':'Informe quantidades, preparo e óleo quando conhecidos.'}</p></div>{editing&&<button disabled={busy} onClick={reset}>Cancelar edição</button>}</div><fieldset className="food-fieldset" disabled={busy}><div className="form-grid"><label>Refeição<select value={entry.meal} onChange={e=>input('meal',e.target.value)}>{meals.map(meal=><option key={meal}>{meal}</option>)}</select></label><label>Foto opcional<input key={entry.id} type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>imageSelected(e.target.files?.[0])}/></label><label className="wide">O que você comeu?<textarea rows="4" maxLength="10000" value={entry.text} onChange={e=>input('text',e.target.value)} placeholder="Ex.: 200 ml de iogurte, 1 scoop de whey e 1 banana. Informe quantidades e preparo."/></label></div>{entry.image&&<div className="food-image"><img src={entry.image} alt="Foto da refeição selecionada"/><div><label className="checkbox-label"><input type="checkbox" checked={imageConsent} onChange={e=>setImageConsent(e.target.checked)}/>Enviar esta foto à IA ao analisar</label><p className="small muted">A foto fica no arquivo privado ao salvar. A análise visual não comprova peso nem ingredientes invisíveis.</p><button onClick={()=>setEntry(value=>({...value,image:null}))}>Remover foto</button></div></div>}
      <div className="report-actions"><button disabled={!diary.configured || !canAnalyze} onClick={()=>analyze()}>Analisar com IA</button><button onClick={()=>setEntry(value=>({...value,analysis:value.analysis || {items:[emptyItem()],notes:'Valores informados manualmente.'}}))}>Informar calorias manualmente</button><button disabled={!entry.text.trim()&&!entry.image} onClick={()=>save(true)}>Salvar com estimativa pendente</button></div>{busy&&<p className="muted" role="status">Processando…</p>}{!diary.configured&&<p className="small muted">IA automática não configurada. Use registro manual, salve pendente ou importe a análise de outra IA.</p>}
      <details className="method"><summary>Analisar em outra IA</summary><button disabled={entry.text.trim().length<3} onClick={()=>run(async()=>setPrompt((await personalApi(`food/${day}/prompt`,{text:entry.text,meal:entry.meal})).prompt))}>Preparar prompt</button>{prompt&&<textarea className="daily-textarea" aria-label="Prompt da refeição" readOnly rows="8" value={prompt}/>}<label className="question-label">Resposta JSON da IA<textarea rows="4" value={manual} onChange={e=>setManual(e.target.value)}/></label><button disabled={!manual.trim() || entry.text.trim().length<3} onClick={()=>analyze(true)}>Importar e revisar</button></details>
      {analysis&&<div className="food-review"><h3>Revise antes de salvar</h3><div className="table-scroll"><table className="food-editor"><thead><tr><th>Alimento e quantidade</th>{Object.values(nutrients).map(label=><th key={label}>{label}</th>)}<th>Remover</th></tr></thead><tbody>{analysis.items.map((item,index)=><tr key={index}><td><input aria-label={`Alimento ${index+1}`} maxLength="300" value={item.name} onChange={e=>editItem(index,'name',e.target.value)}/></td>{Object.keys(nutrients).map(key=><td key={key}><input aria-label={`${nutrients[key]} alimento ${index+1}`} type="number" min="0" max="20000" step="0.1" placeholder="Desconhecido" value={item[key] ?? ''} onChange={e=>editItem(index,key,e.target.value)}/></td>)}<td><button disabled={analysis.items.length<=1} onClick={()=>setEntry(value=>({...value,analysis:{...value.analysis,items:value.analysis.items.filter((_,i)=>i!==index)}}))}>Remover</button></td></tr>)}</tbody></table></div><button onClick={()=>setEntry(value=>({...value,analysis:{...value.analysis,items:[...value.analysis.items,emptyItem()]}}))}>Adicionar alimento</button><label className="question-label">Hipóteses e notas<textarea rows="2" maxLength="5000" value={analysis.notes || ''} onChange={e=>setEntry(value=>({...value,analysis:{...value.analysis,notes:e.target.value}}))}/></label><p className="small muted">Use zero somente quando conhecido. Valor vazio significa estimativa pendente.</p><button className="primary" disabled={!analysis.items.every(item=>item.name.trim()) || (!entry.text.trim()&&!entry.image)} onClick={()=>save(false)}>{editing?'Salvar correção':'Salvar refeição revisada'}</button></div>}
      </fieldset></section>
      <section className="panel"><div className="panel-heading"><div><h2>Refeições de {dayLabel(day)}</h2><p>Editar recalcula os totais. Copiar prepara uma nova refeição para revisão.</p></div></div>{diary.entries.length?diary.entries.map(row=><article className="food-entry" key={row.id}><div className="proposal-heading"><h3>{row.meal}</h3><span className={'tag '+(!row.analysis || row.analysis.items.some(item=>item.kcal==null)?'pending':'completed')}>{!row.analysis || row.analysis.items.some(item=>item.kcal==null)?'Estimativa pendente':'Valores registrados'}</span></div><p className="food-description">{row.text}</p>{row.analysis&&<p className="small muted">{Object.keys(nutrients).map(key=>`${nutrients[key]}: ${format(sum(row.analysis.items,key),0)}${array(row.analysis.items).some(item=>item[key]==null)?' + pendente':''}`).join(' · ')}</p>}{row.image_id&&<details className="method"><summary>Ver foto salva</summary><img className="saved-food-image" src={`/api/food-images/${encodeURIComponent(row.image_id)}`} alt="Foto registrada desta refeição" loading="lazy"/></details>}{row.analysis&&<details className="method"><summary>Alimentos e hipóteses</summary>{row.analysis.items.map((item,index)=><p key={index}>{item.name}: {format(item.kcal)} kcal · P {format(item.protein_g)} g · C {format(item.carbs_g)} g · G {format(item.fat_g)} g</p>)}<p>{row.analysis.notes}</p></details>}<div className="report-actions"><button disabled={busy} onClick={()=>edit(row)}>Editar</button><button disabled={busy} onClick={()=>edit(row,true)}>Copiar</button><button disabled={busy} onClick={()=>run(async()=>{const result=await personalApi(`food/${day}/remove`,{id:row.id,revision:diary.revision});setDiary(value=>({...value,...result}));setMessage('Refeição removida. Você pode restaurar uma versão anterior.');})}>Excluir</button></div></article>):<p className="empty">Nenhuma refeição salva para este dia.</p>}</section>
      <section className="panel"><h2>Encerrar o dia alimentar</h2><p className="small muted">Declare completo quando todas as refeições estiverem registradas. Calorias pendentes continuam limitando o balanço energético.</p>{!diary.entries.length&&<label className="checkbox-label"><input type="checkbox" checked={fasting} disabled={busy} onChange={e=>setFasting(e.target.checked)}/>Declaro que este dia não teve ingestão alimentar</label>}<div className="report-actions"><button className="primary" disabled={busy || (!diary.entries.length&&!fasting)} onClick={()=>run(async()=>{const result=await personalApi(`food/${day}/coverage`,{completeness:'complete',fasting_declared:fasting,revision:diary.revision});setDiary(value=>({...value,...result}));setMessage('Dia declarado completo. Valores pendentes continuam identificados.');})}>Declarar dia completo</button>{diary.completeness==='complete'&&<button disabled={busy} onClick={()=>run(async()=>{const result=await personalApi(`food/${day}/coverage`,{completeness:diary.entries.length?'partial':'empty',fasting_declared:false,revision:diary.revision});setDiary(value=>({...value,...result}));setFasting(false);setMessage('Diário reaberto.');})}>Reabrir diário</button>}</div></section>
      <details className="panel"><summary className="section-summary">Refeições frequentes e receitas</summary><div className="recipe-library">{recipes.map(recipe=><div className="record-row" key={recipe.id}><div><strong>{recipe.title}</strong><p>{recipe.text}</p><span className="small muted">{recipe.servings || 1} porção(ões) na receita</span><label className="recipe-portions">Porções a consumir<input type="number" min="0.1" max="1000" step="0.1" value={portions[recipe.id] ?? 1} onChange={e=>setPortions(v=>({...v,[recipe.id]:e.target.value}))}/></label></div><div className="report-actions"><button disabled={busy} onClick={()=>useRecipe(recipe)}>Usar e revisar</button><button disabled={busy} onClick={()=>run(async()=>{await personalApi(`food-library/${encodeURIComponent(recipe.id)}/remove`,{});await loadLibrary();})}>Remover</button></div></div>)}{!recipes.length&&<p className="empty">Salve uma refeição preparada como referência para as próximas vezes.</p>}<div className="personal-form"><div className="form-grid"><label>Nome da refeição frequente<input value={recipeTitle} maxLength="200" onChange={e=>setRecipeTitle(e.target.value)} placeholder="Ex.: café da manhã habitual"/></label><label>Porções descritas<input type="number" min="1" max="100" value={servings} onChange={e=>setServings(Number(e.target.value))}/></label></div><button disabled={busy || !recipeTitle.trim() || !entry.text.trim() || !entry.analysis || !entry.analysis.items.every(item=>item.name.trim())} onClick={()=>run(async()=>{await personalApi('food-library',{title:recipeTitle,text:entry.text,servings,analysis:entry.analysis});await loadLibrary();setMessage('Refeição salva na biblioteca.');})}>Salvar o rascunho atual na biblioteca</button></div></div></details>
      <details className="panel"><summary className="section-summary">Histórico e restauração</summary><p className="small muted">Restaurar cria uma nova revisão do dia, preservando a trilha de alterações.</p>{array(diary.history).length?array(diary.history).slice().reverse().slice(0,20).map(row=><div className="record-row" key={row.revision}><div><strong>Versão {row.revision}</strong><p>{new Date(row.at).toLocaleString('pt-BR')} · {({save:'Registro',edit:'Correção',remove:'Exclusão',coverage:'Cobertura',restore:'Restauração'})[row.action] || row.action}</p></div><button disabled={busy} onClick={()=>run(async()=>{const result=await personalApi(`food/${day}/restore`,{restore_revision:row.revision,revision:diary.revision});setDiary(value=>({...value,...result}));setFasting(Boolean(result.fasting_declared));reset();setMessage('Versão anterior restaurada como nova revisão.');})}>Restaurar esta versão</button></div>):<p className="empty">As próximas alterações aparecerão aqui.</p>}</details>
    </>}
  </>;
}
