import React, {useEffect, useRef, useState} from 'react';
import DayReview from './DayReview';
import {Modal,PagedList} from './ui';
import {array,dayLabel,ErrorNotice,format,personalApi,StatusNotice,today} from './personalApi';

const nutrients = {kcal:'Calorias (kcal)',protein_g:'Proteína (g)',carbs_g:'Carboidratos (g)',fat_g:'Gorduras (g)'};
const meals = ['Café da manhã','Almoço','Lanche','Jantar','Ceia','Outro'];
const blank = ()=>({id:crypto.randomUUID(),meal:'Lanche',text:'',analysis:null,image:null,save_token:crypto.randomUUID()});
const clone = value=>JSON.parse(JSON.stringify(value));
const draftSignature = (entry,title='',servings=1)=>JSON.stringify({meal:entry.meal,text:entry.text,image:entry.image,title,servings});
const excerpt = (value,length=240)=>value.length>length?value.slice(0,length).trimEnd()+'…':value;
function sum(items,key) {const known=array(items).filter(item=>item[key]!=null);return known.length?known.reduce((value,item)=>value+Number(item[key]),0):null;}
function totalLabel(diary,key) {if(!diary.entries.length)return diary.fasting_declared?'0':'Sem dado';const known=diary.entries.some(entry=>array(entry.analysis?.items).some(item=>item[key]!=null));return known?format(diary.totals[key],0):'Pendente';}
function isPending(row) {return !row.analysis || !array(row.analysis.items).length || row.analysis.items.some(item=>item.kcal==null);}
function FoodEstimate({analysis,resetKey}) {return <><PagedList items={array(analysis.items)} resetKey={resetKey} label="Alimentos estimados">{items=>items.map((item,index)=><p key={index}>{item.name}: {format(item.kcal)} kcal · P {format(item.protein_g)} g · C {format(item.carbs_g)} g · G {format(item.fat_g)} g</p>)}</PagedList>{analysis.notes&&<p>{analysis.notes}</p>}</>;}

export default function FoodDiary({initialDay}) {
  const [day,setDay] = useState(initialDay || today()), [diary,setDiary] = useState(null), [entry,setEntry] = useState(blank), [editing,setEditing] = useState(false), [editorOpen,setEditorOpen] = useState(false);
  const [recipes,setRecipes] = useState([]), [recipeTitle,setRecipeTitle] = useState(''), [servings,setServings] = useState(1), [busy,setBusy] = useState(false), [loading,setLoading] = useState(true), [error,setError] = useState(''), [message,setMessage] = useState(''), [fasting,setFasting] = useState(false);
  const [portions,setPortions] = useState({}), [reviewOpen,setReviewOpen] = useState(false), [reviewState,setReviewState] = useState({busy:false,dirty:false}), [readingImage,setReadingImage] = useState(false);
  const version = useRef(0), operation = useRef(false), initialDraft = useRef('');
  async function load(selectedDay=day) {const result=await personalApi('food/'+selectedDay);if(selectedDay===day){setDiary(result);setFasting(Boolean(result.fasting_declared));}return result;}
  async function loadLibrary() {const value=await personalApi('food-library');setRecipes(array(value.recipes));}
  useEffect(()=>{const request=++version.current;setLoading(true);setDiary(null);setEntry(blank());setEditing(false);setEditorOpen(false);setReviewOpen(false);setError('');setMessage('');personalApi('food/'+day).then(value=>{if(request===version.current){setDiary(value);setFasting(Boolean(value.fasting_declared));}}).catch(e=>{if(request===version.current)setError(e.message);}).finally(()=>{if(request===version.current)setLoading(false);});return()=>{version.current++;};},[day]);
  useEffect(()=>{loadLibrary().catch(()=>{});},[]);
  useEffect(()=>{let active=true;const refresh=()=>personalApi(`nutrition-targets/${day}`).then(targets=>{if(active)setDiary(value=>value?{...value,targets}:value);}).catch(()=>{});const timer=setInterval(refresh,15000);window.addEventListener('focus',refresh);return()=>{active=false;clearInterval(timer);window.removeEventListener('focus',refresh);};},[day]);
  useEffect(()=>{let active=true;const refresh=()=>personalApi('ai/configuration').then(config=>{if(active)setDiary(previous=>previous?{...previous,...config}:previous);}).catch(()=>{});const storage=event=>{if(event.key==='ascentiq-integrations-updated')refresh();};const visible=()=>{if(!document.hidden)refresh();};window.addEventListener('focus',refresh);window.addEventListener('storage',storage);window.addEventListener('ascentiq-integrations-changed',refresh);document.addEventListener('visibilitychange',visible);return()=>{active=false;window.removeEventListener('focus',refresh);window.removeEventListener('storage',storage);window.removeEventListener('ascentiq-integrations-changed',refresh);document.removeEventListener('visibilitychange',visible);};},[]);
  async function run(action) {if(operation.current)return null;operation.current=true;setBusy(true);setError('');setMessage('');try{return await action();}catch(e){setError(e.message);if(e.status===409 || /diário mudou/i.test(e.message))await load().catch(()=>{});return null;}finally{operation.current=false;setBusy(false);}}
  function reset(){setEntry(blank());setEditing(false);setRecipeTitle('');setServings(1);}
  function openEditor(value=blank(),isEditing=false,isUnsaved=false) {setEntry(value);setEditing(isEditing);setRecipeTitle('');setServings(1);initialDraft.current=draftSignature(isUnsaved?blank():value);setError('');setMessage('');setEditorOpen(true);}
  function closeEditor(){setEditorOpen(false);reset();}
  function input(key,value){setEntry(previous=>({...previous,[key]:value,save_token:crypto.randomUUID(),...(key==='text'?{analysis:null}:{})}));}
  async function save(){if(readingImage)return;await run(async()=>{const result=await personalApi(`food/${day}/save`,{id:entry.id,meal:entry.meal,text:entry.text.trim().length>=3?entry.text.trim():'Refeição registrada por foto. '+entry.text.trim(),image:entry.image,estimate_on_save:true,save_token:entry.save_token,revision:diary.revision});setDiary(value=>({...value,...result}));setFasting(Boolean(result.fasting_declared));if(result.analysis_status==='estimated'){closeEditor();setMessage('Refeição salva com estimativa da IA. O total do dia foi atualizado.');}else{const stored=array(result.entries).find(row=>row.id===entry.id);const saved={...entry,...stored,image:entry.image,save_token:crypto.randomUUID()};setEntry(saved);setEditing(true);initialDraft.current=draftSignature(saved);setMessage('Refeição salva. A estimativa ficou pendente.');setError('A IA não concluiu a estimativa. '+(result.analysis_error || 'Salve novamente para tentar.'));}});}
  async function imageSelected(file){setError('');if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)){setError('Escolha uma foto JPEG, PNG ou WebP.');return;}if(file.size>6*1024*1024){setError('A foto deve ter até 6 MB.');return;}setReadingImage(true);try{const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=16384)binary+=String.fromCharCode(...bytes.subarray(i,i+16384));setEntry(value=>({...value,image:`data:${file.type};base64,${btoa(binary)}`,analysis:null,save_token:crypto.randomUUID()}));}catch{setError('Não foi possível ler a foto.');}finally{setReadingImage(false);}}
  function edit(row,copy=false){openEditor({...clone(row),analysis:row.analysis || row.analysis_proposal,id:copy?crypto.randomUUID():row.id,image:null,image_id:copy?null:row.image_id,save_token:crypto.randomUUID()},!copy,copy);setMessage(copy?'Cópia da descrição preparada. Revise, adicione uma foto se desejar e salve como uma nova refeição.':'Edite a descrição e salve. A IA recalcula a estimativa automaticamente.');}
  function useRecipe(recipe) {const selected=Number(portions[recipe.id] || 1),yielded=Number(recipe.servings || 1);if(!Number.isFinite(selected) || selected<=0 || selected>1000){setError('Informe de 0,1 a 1.000 porções para usar a receita.');return;}const factor=selected/yielded,analysis=recipe.analysis?clone(recipe.analysis):null;if(analysis){analysis.items=analysis.items.map(item=>({...item,name:`${item.name} · ${selected} de ${yielded} porções`,...Object.fromEntries(Object.keys(nutrients).map(key=>[key,item[key]==null?null:Math.round(Number(item[key])*factor*10)/10]))}));analysis.notes=`${analysis.notes || ''}\nReceita escalada para ${selected} de ${yielded} porções. Revise as quantidades.`;}openEditor({...blank(),text:`${recipe.text}\nConsumi ${selected} de ${yielded} porções da receita.`,analysis},false,true);setMessage('Porção da receita preparada. Confira e salve a refeição.');}
  async function saveRecipe(){await run(async()=>{await personalApi('food-library',{title:recipeTitle.trim(),text:entry.text,servings,analysis:entry.analysis});await loadLibrary();setRecipeTitle('');setServings(1);setMessage('Refeição salva na biblioteca.');});}
  const pending = diary?.pending_count || 0, analysis = entry.analysis, canSave = entry.text.trim().length>=3 || Boolean(entry.image);
  const dirty = draftSignature(entry,recipeTitle,servings)!==initialDraft.current;
  return <><ErrorNotice error={editorOpen?'':error}/><StatusNotice message={editorOpen?'':message}/><section className="panel"><div className="panel-heading"><div><h2>Nutrition</h2><p>consumo e metas</p></div></div><div className="filters"><label>Dia<input type="date" value={day} disabled={busy || editorOpen || reviewOpen} onChange={e=>setDay(e.target.value)}/></label><button disabled={busy || loading} onClick={()=>run(load)}>Atualizar o diário</button><span className={'tag '+(diary?.completeness==='complete'?'completed':'pending')}>{({empty:'Sem registros',partial:'Diário parcial',complete:'Dia declarado completo'})[diary?.completeness] || 'Consultando'}</span></div></section>{loading&&<p className="muted" role="status">Reunindo seu diário…</p>}
    {diary&&<><div className="metrics four daily-nutrition-progress">{Object.entries(nutrients).map(([key,label])=>{const target=diary.targets?.[key],known=Boolean(diary.fasting_declared) || diary.entries.some(row=>array(row.analysis?.items).some(item=>item[key]!=null)),consumed=known?Number(diary.totals[key] || 0):null,remaining=target!=null&&known?target-consumed:null;return <div className="metric" key={key}><div className="eyebrow">{label}</div><div className="metric-value">{diary.entries.length?totalLabel(diary,key):diary.fasting_declared?'0':'Sem dado'}{target!=null&&<span className="target-total"> / {format(target,0)}</span>}</div>{target!=null&&known&&<progress aria-label={`Progresso de ${label}`} max={target} value={Math.min(target,consumed)}/>}<p className="small muted">{remaining!=null?(remaining>=0?`Faltam ${format(remaining,0)} ${key==='kcal'?'kcal':'g'}`:`${format(-remaining,0)} ${key==='kcal'?'kcal':'g'} acima da meta`):!known?(diary.entries.length?'Estimativa pendente · saldo ainda indisponível':'Registre o consumo para calcular o saldo'):'Total registrado · meta ainda não disponível'}{known&&diary.unknown_nutrients?.[key]?` · saldo provisório, ${diary.unknown_nutrients[key]} estimativa(s) pendente(s)`:''}</p></div>;})}</div><div className="nutrition-target-notice"><p className="small muted">Registrado / meta do dia · {diary.targets?.automatic?'meta atualizada diariamente conforme peso, objetivo e treinos':'meta automática pausada'}.{diary.targets?.updated_at?` Última atualização: ${new Date(diary.targets.updated_at).toLocaleString('pt-BR')}.`:''}</p>{diary.targets?.message&&<p role="status">{diary.targets.message}</p>}{diary.targets?.reason&&<details className="method"><summary>Como sua meta foi definida</summary><p>{diary.targets.reason}</p>{array(diary.targets.limitations).map((text,index)=><p className="small muted" key={index}>{text}</p>)}</details>}</div>{(!diary.complete_nutrition || pending>0)&&<p className="small muted" role="status">{pending?`${pending} refeição(ões) com estimativa pendente. `:'Diário em andamento. '}O subtotal conhecido ainda pode ser parcial.</p>}
      <section className="panel"><div className="panel-heading"><div><h2>Refeições de {dayLabel(day)}</h2><p>Salve a descrição ou a foto para estimar automaticamente.</p></div><div className="report-actions"><button className="primary" disabled={busy} onClick={()=>openEditor()}>Adicionar refeição</button><button disabled={busy} onClick={()=>{setReviewState({busy:false,dirty:false});setReviewOpen(true);}}>Analisar meu dia</button></div></div>{diary.entries.length?<PagedList items={diary.entries} resetKey={day} label="Refeições">{items=><div className="meal-grid">{items.map(row=><article className="food-entry meal-card" key={row.id}><div className="proposal-heading"><h3>{row.meal}</h3><span className={'tag '+(isPending(row)?'pending':'completed')}>{isPending(row)?(row.analysis_proposal?'Estimativa para revisão':'Estimativa pendente'):(row.source==='ai_estimated'?'Estimativa por IA':'Valores registrados')}</span></div>{row.image_id&&<img className="saved-food-image meal-photo" src={`/api/food-images/${encodeURIComponent(row.image_id)}`} alt={`Foto de ${row.meal}`} loading="lazy"/>}<p className="food-description">{excerpt(row.text)}</p>{row.analysis&&<p className="small muted">{Object.keys(nutrients).map(key=>`${nutrients[key]}: ${format(sum(row.analysis.items,key),0)}${array(row.analysis.items).some(item=>item[key]==null)?' + pendente':''}`).join(' · ')}</p>}{row.analysis&&<details className="method"><summary>Alimentos e hipóteses</summary><FoodEstimate analysis={row.analysis} resetKey={row.id}/></details>}<div className="report-actions"><button disabled={busy} onClick={()=>edit(row)}>Editar</button><button disabled={busy} onClick={()=>edit(row,true)}>Copiar</button><button disabled={busy} onClick={()=>run(async()=>{const result=await personalApi(`food/${day}/remove`,{id:row.id,revision:diary.revision});setDiary(value=>({...value,...result}));setMessage('Refeição removida.');})}>Excluir</button></div></article>)}</div>}</PagedList>:<p className="empty">Nenhuma refeição salva para este dia.</p>}</section>
      <section className="panel"><h2>Cobertura do dia</h2><p className="small muted">Declare completo quando todas as refeições estiverem registradas. Estimativas pendentes continuam identificadas.</p>{!diary.entries.length&&<label className="checkbox-label"><input type="checkbox" checked={fasting} disabled={busy} onChange={e=>setFasting(e.target.checked)}/>Declaro que este dia não teve ingestão alimentar</label>}<div className="report-actions"><button className="primary" disabled={busy || (!diary.entries.length&&!fasting)} onClick={()=>run(async()=>{const result=await personalApi(`food/${day}/coverage`,{completeness:'complete',fasting_declared:fasting,revision:diary.revision});setDiary(value=>({...value,...result}));setMessage('Dia declarado completo. Valores pendentes continuam identificados.');})}>Declarar dia completo</button>{diary.completeness==='complete'&&<button disabled={busy} onClick={()=>run(async()=>{const result=await personalApi(`food/${day}/coverage`,{completeness:diary.entries.length?'partial':'empty',fasting_declared:false,revision:diary.revision});setDiary(value=>({...value,...result}));setFasting(false);setMessage('Diário reaberto.');})}>Reabrir diário</button>}</div></section>
      <details className="panel"><summary className="section-summary">Refeições frequentes e receitas</summary><div className="recipe-library">{recipes.length?<PagedList items={recipes} resetKey="food-library" label="Receitas">{items=>items.map(recipe=><div className="record-row" key={recipe.id}><div><strong>{recipe.title}</strong><p>{excerpt(recipe.text)}</p><span className="small muted">{recipe.servings || 1} porção(ões) na receita</span><label className="recipe-portions">Porções a consumir<input type="number" min="0.1" max="1000" step="0.1" disabled={busy} value={portions[recipe.id] ?? 1} onChange={e=>setPortions(v=>({...v,[recipe.id]:e.target.value}))}/></label></div><div className="report-actions"><button disabled={busy} onClick={()=>useRecipe(recipe)}>Usar e revisar</button><button disabled={busy} onClick={()=>run(async()=>{await personalApi(`food-library/${encodeURIComponent(recipe.id)}/remove`,{});await loadLibrary();setMessage('Receita removida da biblioteca.');})}>Remover</button></div></div>)}</PagedList>:<p className="empty">Abra uma refeição estimada para salvá-la como referência para as próximas vezes.</p>}</div></details>
      {editorOpen&&<Modal title={editing?'Editar refeição':'Adicionar refeição'} onClose={closeEditor} busy={busy || readingImage} dirty={dirty} className="meal-modal"><ErrorNotice error={error}/><StatusNotice message={message}/><fieldset className="food-fieldset" disabled={busy || readingImage}><div className="form-grid"><label>Refeição<select value={entry.meal} onChange={e=>input('meal',e.target.value)}>{meals.map(meal=><option key={meal}>{meal}</option>)}</select></label><label>Foto opcional<input key={entry.id} type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>imageSelected(e.target.files?.[0])}/></label><label className="wide">O que você comeu?<textarea autoFocus rows="4" maxLength="10000" value={entry.text} onChange={e=>input('text',e.target.value)} placeholder="Ex.: 200 ml de iogurte, 1 scoop de whey e 1 banana. Informe quantidades e preparo."/></label></div>{readingImage&&<p className="small muted" role="status">Carregando a foto…</p>}{entry.image&&<div className="food-image"><img src={entry.image} alt="Foto da refeição selecionada"/><div><p className="small muted">A IA considera a foto e a descrição. Informe o peso quando conhecido.</p><button onClick={()=>setEntry(value=>({...value,image:null,analysis:null,save_token:crypto.randomUUID()}))}>Remover foto selecionada</button></div></div>}{!entry.image&&entry.image_id&&<p className="small muted">A foto já cadastrada será mantida.</p>}
      <div className="report-actions"><button className="primary" disabled={!canSave || busy} onClick={save}>{busy?'Salvando…':editing?'Salvar alterações':'Salvar refeição'}</button></div>{diary.configured&&<p className="small muted">{diary.local?'Ollama local · sem cobrança por chamada':'OpenAI · API paga'} · {diary.model}. Ao salvar, a IA calcula e registra a estimativa.</p>}{busy&&<p className="muted" role="status">Concluindo a operação. A estimativa de uma refeição pode levar alguns instantes…</p>}{!diary.configured&&<p className="small muted">A refeição será salva com estimativa pendente. Configure a IA em Dados e fontes.</p>}
      {analysis&&<details className="method"><summary>Última estimativa</summary><FoodEstimate analysis={analysis} resetKey={entry.id}/><p className="small muted">Salvar recalcula os valores a partir da descrição e da foto.</p></details>}
      {analysis&&<details className="method"><summary>Salvar como refeição frequente</summary><div className="form-grid"><label>Nome da refeição frequente<input value={recipeTitle} maxLength="200" onChange={e=>setRecipeTitle(e.target.value)} placeholder="Ex.: café da manhã habitual"/></label><label>Porções descritas<input type="number" min="1" max="100" value={servings} onChange={e=>setServings(Number(e.target.value))}/></label></div><button disabled={busy || !recipeTitle.trim() || !entry.text.trim() || !Number.isFinite(servings) || servings<1 || servings>100 || !array(analysis.items).length || !analysis.items.every(item=>item.name.trim())} onClick={saveRecipe}>Salvar na biblioteca</button><p className="small muted">A biblioteca guarda esta descrição e estimativa. Para registrar o consumo no dia, use Salvar refeição.</p></details>}
      </fieldset></Modal>}
      {reviewOpen&&<Modal title="Análise do dia" onClose={()=>setReviewOpen(false)} busy={reviewState.busy} dirty={reviewState.dirty}><DayReview day={day} revision={diary.revision} onStateChange={setReviewState}/></Modal>}
    </>}
  </>;
}
