import React,{useEffect,useRef,useState} from 'react';
import {personalApi,dayLabel,format,today} from './personalApi';
export default function Frequency({revision}) {
  const currentYear=Number(today().slice(0,4));
  const [year,setYear]=useState(currentYear),[result,setResult]=useState(null),[error,setError]=useState(''),[active,setActive]=useState(null);
  const root=useRef(null);
  useEffect(()=>{setActive(null);},[year]);
  useEffect(()=>{let alive=true;setError('');const load=()=>personalApi(`frequency?year=${year}`).then(v=>{if(alive){setResult(v);setActive(previous=>previous?{...previous,row:v.days.find(row=>row.date===previous.row.date) || previous.row}:null);}}).catch(e=>{if(alive)setError(e.message);});load();window.addEventListener('ascentiq-personal-changed',load);return()=>{alive=false;window.removeEventListener('ascentiq-personal-changed',load);};},[year,revision]);
  useEffect(()=>{const close=e=>{if(!root.current?.contains(e.target))setActive(null);};document.addEventListener('pointerdown',close);return()=>document.removeEventListener('pointerdown',close);},[]);
  const ready=result?.year===year;
  const days=ready?result.days:[],offset=days.length?new Date(days[0].date+'T12:00:00Z').getUTCDay():0;
  const level=n=>Math.min(4,n);
  function show(row,event){const box=event.currentTarget.getBoundingClientRect();setActive({row,x:Math.max(12,Math.min(box.left-100,window.innerWidth-252)),y:box.bottom+8,above:box.bottom>window.innerHeight-240});}
  return <section className="panel frequency" ref={root} onKeyDown={e=>{if(e.key==='Escape')setActive(null);}}>
    <div className="panel-heading"><div><h2>Frequência dos registros</h2><p>{ready?`${format(days.reduce((n,r)=>n+r.count,0),0)} pontos em ${days.filter(r=>r.count>0).length} dias · ${year}`:'Carregando registros…'}</p></div><label>Ano<select aria-label="Ano da frequência" value={year} onChange={e=>setYear(Number(e.target.value))}>{Array.from({length:8},(_,i)=>currentYear-i).map(y=><option key={y}>{y}</option>)}</select></label></div>
    {error&&<p role="alert">{error}</p>}{ready&&<><div className="frequency-scroll"><div className="frequency-months" style={{gridTemplateColumns:`repeat(${Math.ceil((days.length+offset)/7)},16px)`}}>{days.filter(r=>r.date.endsWith('-01')).map(r=><span key={r.date} style={{gridColumn:Math.floor((days.indexOf(r)+offset)/7)+1}}>{new Date(r.date+'T12:00:00').toLocaleDateString('pt-BR',{month:'short'})}</span>)}</div><div className="frequency-grid">{Array.from({length:offset},(_,i)=><span key={'blank'+i}/>)}{days.map(row=><button key={row.date} className={`frequency-cell level-${level(row.count)}`} aria-label={`${dayLabel(row.date)}: ${row.count} categorias registradas`} aria-describedby={active?.row.date===row.date?'frequency-tooltip':undefined} onMouseEnter={e=>show(row,e)} onMouseLeave={()=>setActive(null)} onFocus={e=>show(row,e)} onBlur={()=>setActive(null)} onClick={e=>show(row,e)}/>)}</div></div><div className="frequency-footer"><span>Até 4 pontos por dia: sono, alimentação, corrida e força. Cada categoria vale 1 ponto.</span><div>Menos {[0,1,2,3,4].map(n=><i key={n} className={`frequency-cell level-${n}`}/>)} Mais</div></div></>}
    {active&&<div id="frequency-tooltip" role="tooltip" className="frequency-tooltip" style={{left:active.x,...(active.above?{bottom:Math.max(12,window.innerHeight-active.y+30)}:{top:active.y})}}><strong>{dayLabel(active.row.date)}</strong><span>{active.row.count} de 4 categorias</span>{active.row.count===0?<p>Nenhum registro.</p>:<dl>{active.row.sleep_minutes!=null&&<><dt>Sono</dt><dd>{active.row.sleep_minutes!=null?`${format(active.row.sleep_minutes/60)} h`:'Sem duração registrada'}</dd></>}{active.row.meal_count>0&&<><dt>Alimentação</dt><dd>{active.row.meal_count?`${active.row.kcal!=null?format(active.row.kcal,0)+' kcal':'Estimativa pendente'}${active.row.pending_count?' · '+active.row.pending_count+' pendente(s)':''}`:'Sem registro'}</dd></>}{active.row.running_count>0&&<><dt>Corrida</dt><dd>{active.row.running_count?(active.row.running_km!=null?format(active.row.running_km)+' km':'Distância não informada'):'Sem registro'}</dd></>}{active.row.strength_count>0&&<><dt>Força</dt><dd>{active.row.strength_count?`${active.row.strength_count} sessão(ões)`:'Sem registro'}</dd></>}</dl>}</div>}
  </section>;
}
