import React, {useEffect, useState} from 'react';
import Timeline from './Timeline';
import {array,dayLabel,ErrorNotice,format,optionalNumber,PageHeading,personalApi,PersonalLoading,StatusNotice,today,usePersonal} from './personalApi';

const types = {fat_loss:'Reduzir gordura',weight_gain:'Ganhar peso',maintenance:'Manter composição',strength:'Força',endurance:'Resistência esportiva',sleep:'Sono',consistency:'Consistência',custom:'Objetivo pessoal'};
const metricUnits = {weight_kg:'kg de peso',waist_cm:'cm de cintura',body_fat_pct:'% de gordura corporal',weekly_sessions:'sessões por semana',distance_km:'km',sleep_hours:'horas de sono'};
const statuses = {active:'Ativo',paused:'Pausado',completed:'Concluído',archived:'Arquivado'};
const proposalStatus = {pending:'Aguardando decisão',accepted:'Aceita',rejected:'Rejeitada',stale:'Contexto alterado'};
const fresh = ()=>({description:'',type:'fat_loss',priority:1,status:'active',target_metric:'weight_kg',target_value:'',target_kcal:'',desired_weekly_change_kg:'',due_date:'',preserve:[],notes:''});
function Plan({value}) { return value ? <div className="plan-summary"><strong>{value.target_kcal != null ? `${format(value.target_kcal,0)} kcal por dia` : 'Sem meta calórica'}</strong><span>{value.protein_g!=null?`Proteína: ${format(value.protein_g,0)} g por dia`:"Proteína ainda sem meta"}</span><span>Versão {value.version || 1} · vigência {dayLabel(value.effective_from)}</span><span>Próxima revisão: {dayLabel(value.next_review_date)}</span>{value.reason && <p>{value.reason}</p>}{array(value.limitations).map((text,index)=><p className="small muted" key={index}>{text}</p>)}</div> : <p className="small muted">Não há plano vigente para esta referência.</p>; }

function ManualPlan({model,goals}) {
  const [value,setValue] = useState({goal_id:'',effective_from:today(),next_review_date:'',target_kcal:'',protein_g:'',carbs_g:'',fat_g:'',reason:'Referência informada pelo usuário.'});
  const [busy,setBusy] = useState(false), [error,setError] = useState(''), [message,setMessage] = useState('');
  const input = key=>e=>setValue(row=>({...row,[key]:e.target.value}));
  async function submit(event){event.preventDefault();setBusy(true);setError('');setMessage('');try{const record={...value,goal_id:value.goal_id || goals.find(goal=>goal.status==='active')?.id,...Object.fromEntries(['target_kcal','protein_g','carbs_g','fat_g'].map(key=>[key,optionalNumber(value[key])])),method:'user_declared',status:'active'};if(!record.next_review_date)delete record.next_review_date;await model.save('plans',record);setMessage('Nova versão do plano registrada com a vigência escolhida.');}catch(e){setError(e.message);}finally{setBusy(false);}}
  return <details className="panel"><summary className="section-summary">Registrar um plano ou orientação informada</summary><p className="small muted">Use referências pessoais ou profissionais. A nova versão tem vigência e preserva os planos anteriores.</p><ErrorNotice error={error}/><StatusNotice message={message}/><form className="personal-form" onSubmit={submit}><div className="form-grid"><label>Objetivo<select value={value.goal_id || goals.find(goal=>goal.status==='active')?.id || ''} onChange={input('goal_id')} required><option value="">Selecione um objetivo</option>{goals.filter(goal=>goal.status==='active').map(goal=><option value={goal.id} key={goal.id}>{goal.description}</option>)}</select></label><label>Início da vigência<input type="date" value={value.effective_from} onChange={input('effective_from')} required/></label><label>Próxima revisão<input type="date" value={value.next_review_date} onChange={input('next_review_date')}/></label><label>Meta energética (kcal/dia)<input type="number" min="500" max="10000" value={value.target_kcal} onChange={input('target_kcal')}/></label>{[['protein_g','Proteína (g/dia)'],['carbs_g','Carboidratos (g/dia)'],['fat_g','Gorduras (g/dia)']].map(([key,label])=><label key={key}>{label}<input type="number" min="0" max="1000" step="1" value={value[key]} onChange={input(key)}/></label>)}<label className="wide">Origem e motivo<textarea required rows="2" maxLength="5000" value={value.reason} onChange={input('reason')}/></label></div><button className="primary" disabled={busy || !goals.some(goal=>goal.status==='active')}>{busy?'Salvando…':'Registrar versão do plano'}</button></form></details>;
}

export default function Goals() {
  const [day,setDay] = useState(today()), model = usePersonal(day,30);
  const [form,setForm] = useState(fresh), [showForm,setShowForm] = useState(false), [busy,setBusy] = useState(false), [error,setError] = useState(''), [message,setMessage] = useState('');
  const goals = array(model.state.goals).sort((a,b)=>(a.priority || 1)-(b.priority || 1));
  const proposals = array(model.summary.proposals || model.state.proposals).sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at)));
  const change = key=>e=>setForm(v=>({...v,[key]:e.target.value}));
  async function run(action,notice) {setBusy(true);setError('');setMessage('');try{await action();await model.load();if(notice)setMessage(notice);}catch(e){setError(e.message);if(e.status===409)await model.load().catch(()=>{});}finally{setBusy(false);}}
  async function submit(event) {event.preventDefault();await run(async()=>{await model.save('goals',{...form,priority:Number(form.priority),...Object.fromEntries(['target_value','target_kcal','desired_weekly_change_kg'].map(key=>[key,optionalNumber(form[key])])),preserve:array(form.preserve).map(x=>x.trim()).filter(Boolean),due_date:form.due_date || null});setForm(fresh());setShowForm(false);},'Objetivo salvo. O plano inicial foi atualizado quando havia dados suficientes.');}
  const active = model.summary.active_plan;
  const automatic = model.state?.preferences?.auto_nutrition_targets !== false;
  useEffect(()=>{if(!automatic || !model.summary.active_goal)return;const timer=setInterval(()=>model.load().catch(()=>{}),15000);return()=>clearInterval(timer);},[automatic,day,model.load,model.summary.active_goal?.id]);
  const progress = model.summary.progress || {};
  return <><PageHeading kicker="OBJETIVO / PLANO / ADAPTAÇÃO" title="Uma direção clara. Ajustes com motivo.">Defina o que quer alcançar e o que deseja preservar ao longo do caminho.</PageHeading><div className="filters"><label>Referência da revisão<input type="date" value={day} onChange={e=>setDay(e.target.value)}/></label><button className="primary" disabled={busy || model.loading} onClick={()=>run(()=>personalApi('personal/review',{day}),'Revisão concluída. Confira a proposta e os limites dos dados.')}>{busy?'Processando…':'Revisar progresso'}</button><button onClick={()=>{setForm(fresh());setShowForm(v=>!v);}}>{showForm?'Fechar formulário':'Criar objetivo'}</button></div><PersonalLoading model={model}/><ErrorNotice error={error}/><StatusNotice message={message}/>
    {model.value && <>
      {showForm&&<section className="panel"><h2>{form.id?'Editar objetivo':'Novo objetivo'}</h2><form className="personal-form" onSubmit={submit}><div className="form-grid"><label className="wide">Descrição<input required maxLength="1000" value={form.description} onChange={change('description')} placeholder="Ex.: reduzir gordura preservando força e disposição"/></label><label>Tipo<select value={form.type} onChange={change('type')}>{Object.entries(types).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Prioridade · 1 é a principal<input type="number" min="1" max="20" value={form.priority} onChange={change('priority')}/></label><label>Indicador<select value={form.target_metric || ''} onChange={change('target_metric')}><option value="">Sem indicador numérico</option><option value="weight_kg">Peso (kg)</option><option value="waist_cm">Cintura (cm)</option><option value="body_fat_pct">Gordura corporal (%)</option><option value="weekly_sessions">Sessões por semana</option><option value="distance_km">Distância (km)</option><option value="sleep_hours">Sono (horas)</option></select></label><label>Valor desejado<input type="number" min="0" step="0.1" value={form.target_value ?? ''} onChange={change('target_value')}/></label><label>Data desejada<input type="date" value={form.due_date || ''} onChange={change('due_date')}/></label><label>Meta energética informada (kcal)<input type="number" min="500" max="10000" value={form.target_kcal ?? ''} onChange={change('target_kcal')}/></label><label>Variação semanal desejada (kg)<input type="number" min="-0.5" max="0.5" step="0.05" value={form.desired_weekly_change_kg ?? ''} onChange={change('desired_weekly_change_kg')} placeholder="Negativo para perda"/></label><label>Estado<select value={form.status} onChange={change('status')}>{Object.entries(statuses).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="wide">O que preservar? Separar por vírgula<input value={array(form.preserve).join(', ')} onChange={e=>setForm(v=>({...v,preserve:e.target.value.split(',').map(x=>x.trim())}))} placeholder="Força, desempenho, recuperação…"/></label><label className="wide">Notas<textarea rows="3" value={form.notes || ''} onChange={change('notes')}/></label></div><p className="small muted">O prazo é uma preferência; a proposta deve respeitar os dados, a qualidade da cobertura e suas prioridades.</p><div className="report-actions"><button className="primary" disabled={busy}>Salvar objetivo</button><button type="button" onClick={()=>{setForm(fresh());setShowForm(false);}}>Cancelar</button></div></form></section>}
      <section className="panel"><h2>Meta alimentar automática</h2><label className="checkbox-label"><input type="checkbox" checked={automatic} disabled={busy} onChange={e=>run(()=>model.save('preferences',{...model.state.preferences,auto_nutrition_targets:e.target.checked}),e.target.checked?'Atualização automática ativada.':'Atualização automática pausada.')}/>Usar IA local para atualizar calorias e proteína diariamente</label><p className="small muted">O objetivo, o peso e o resumo dos treinos orientam a meta. Alterações no perfil ou no objetivo iniciam um novo cálculo. O histórico permanece disponível; falhas preservam a última meta.</p>{model.value.nutrition_targets?.message&&<p className="small muted" role="status">{model.value.nutrition_targets.message}</p>}</section><div className="split"><section className="panel"><div className="panel-heading"><div><h2>Plano vigente</h2><p>Referências usadas a partir da data de vigência.</p></div>{active?.status&&<span className={'tag '+active.status}>{active.status==='active'?'Ativo':active.status==='provisional'?'Provisório':active.status}</span>}</div><Plan value={active}/></section><section className="panel"><h2>Progresso observado</h2><div className="context-grid"><div><span>Medidas de peso no período</span><b>{progress.weight_measurements ?? 0}</b></div><div><span>Variação observada</span><b>{progress.weight_change_kg != null ? `${format(progress.weight_change_kg,2)} kg` : 'Sem dado'}</b></div><div><span>Variação por semana</span><b>{progress.weekly_change_kg != null ? `${format(progress.weekly_change_kg,2)} kg` : 'Sem dado'}</b></div><div><span>Dias com alimentação completa</span><b>{model.summary.coverage?.food_complete_days ?? 0}</b></div></div><p className="small muted">Uma mudança isolada não sustenta um ajuste. A revisão considera a política e a cobertura do período.</p></section></div>
      <section className="panel"><div className="panel-heading"><div><h2>Seus objetivos</h2><p>Objetivos pausados ou concluídos preservam a história.</p></div></div>{goals.length ? goals.map(goal=><div className="record-row" key={goal.id}><div><span className={'tag '+goal.status}>{statuses[goal.status] || goal.status}</span><h3>{goal.description}</h3><p>{types[goal.type] || goal.type} · prioridade {goal.priority || 1}{goal.target_value!=null?` · alvo ${format(goal.target_value)} ${metricUnits[goal.target_metric] || 'no indicador definido'}`:''}{goal.due_date?` · ${dayLabel(goal.due_date)}`:''}</p>{array(goal.preserve).length>0&&<p className="small muted">Preservar: {goal.preserve.join(', ')}</p>}</div><div className="report-actions"><button onClick={()=>{setForm({...fresh(),...goal});setShowForm(true);window.scrollTo({top:0,behavior:'smooth'});}}>Editar</button>{goal.status==='active'&&<button disabled={busy} onClick={()=>run(()=>model.save('goals',{...goal,status:'paused'}),'Objetivo pausado.')}>Pausar</button>}{goal.status==='paused'&&<button disabled={busy} onClick={()=>run(()=>model.save('goals',{...goal,status:'active'}),'Objetivo retomado.')}>Retomar</button>}{['active','paused'].includes(goal.status)&&<button disabled={busy} onClick={()=>run(()=>model.save('goals',{...goal,status:'completed'}),'Objetivo concluído e preservado no histórico.')}>Concluir</button>}{goal.status!=='archived'&&<button disabled={busy} onClick={()=>run(()=>model.save('goals',{...goal,status:'archived'}),'Objetivo arquivado.')}>Arquivar</button>}</div></div>) : <div className="empty"><p>Você ainda não definiu um objetivo.</p><button onClick={()=>setShowForm(true)}>Criar primeiro objetivo</button></div>}</section>
      <section className="panel"><div className="panel-heading"><div><h2>Propostas de adaptação</h2><p>Confira a evidência antes de aceitar. Rejeitar preserva o plano vigente.</p></div></div>{proposals.length ? proposals.slice(0,15).map(proposal=><article className="proposal-card" key={proposal.id}><div className="proposal-heading"><h3>{proposal.action==='adjust'?'Ajustar o plano':proposal.action==='collect_data'?'Registrar mais dados':'Manter o plano'}</h3><span className={'tag '+proposal.status}>{proposalStatus[proposal.status] || proposal.status}</span></div><p>{proposal.reason}</p>{proposal.suggested_plan && <Plan value={proposal.suggested_plan}/>}<details className="method"><summary>Ver evidência e limitações</summary><div className="evidence-grid">{Object.entries(proposal.evidence || {}).map(([key,value])=><p key={key}><span>{({food_complete_days:'Dias alimentares completos',weight_measurements:'Medidas de peso',weekly_change_kg:'Variação semanal (kg)',avg_deficit_kcal:'Déficit médio (kcal)',days:'Dias analisados',balance_usable_days:'Dias com balanço utilizável'})[key] || key.replaceAll('_',' ')}</span><strong>{typeof value==='object'?JSON.stringify(value):String(value ?? 'Sem dado')}</strong></p>)}</div>{array(proposal.limitations).map((text,index)=><p key={index}>{text}</p>)}</details>{proposal.status==='pending'&&<div className="report-actions"><button className="primary" disabled={busy} onClick={()=>run(()=>personalApi(`personal/proposals/${encodeURIComponent(proposal.id)}/decision`,{decision:'accepted',day}),'Proposta aceita. Confira a nova vigência do plano.')}>Aceitar proposta</button><button disabled={busy} onClick={()=>run(()=>personalApi(`personal/proposals/${encodeURIComponent(proposal.id)}/decision`,{decision:'rejected',day}),'Proposta rejeitada. O plano foi preservado.')}>Rejeitar</button></div>}{proposal.status==='stale'&&<p className="notice">Os dados mudaram. Faça uma nova revisão antes de decidir.</p>}</article>) : <p className="empty">Faça uma revisão para avaliar seu progresso e receber uma proposta fundamentada.</p>}</section>
      <details className="panel"><summary className="section-summary">Histórico de planos e decisões</summary><Timeline state={model.state} day={day}/></details>
      {array(model.state.plans).filter(plan=>plan.status==='active' && plan.effective_from>day).length>0&&<section className="panel"><h2>Planos com vigência futura</h2>{array(model.state.plans).filter(plan=>plan.status==='active' && plan.effective_from>day).sort((a,b)=>a.effective_from.localeCompare(b.effective_from)).slice(0,5).map(plan=><Plan key={plan.id} value={plan}/>)}</section>}
      <ManualPlan model={model} goals={goals}/>
    </>}
  </>;
}
