import React, {useEffect, useRef, useState} from 'react';
import DayReview from './DayReview';
import Frequency from './Frequency';
import {InfoButton,Modal,PagedList} from './ui';
import {array,dayLabel,ErrorNotice,format,optionalNumber,PageHeading,personalApi,PersonalLoading,StatusNotice,today,usePersonal} from './personalApi';

const numeric = ['height_cm','weight_kg','manual_tdee_kcal'];
const defaults = {review_days:14,review_frequency_days:7,min_complete_days:10,min_weight_measurements:4,adjustment_kcal:100,review_reminders:true,energy_method:'auto'};
const intakeStatus = {none:'Sem registros',empty:'Sem registros',partial:'Diário parcial',complete:'Dia completo',pending:'Calorias pendentes'};
const coverageNames = {full:'Completa',complete:'Completa',partial:'Parcial',unknown:'Desconhecida'};
const sourceNames = {profile_model:'Modelo a partir do perfil',profile_declared:'Referência diária informada',manual:'Registro manual',garmin:'Garmin Connect',garmin_daily:'Garmin · sinais diários',wearable:'Relógio ou plataforma',unknown:'Fonte desconhecida'};
const methodNames = {personal_energy_mifflin_v1:'Equação de Mifflin com fator de atividade',declared_profile_daily_total_v1:'Total diário informado no perfil',daily_total_v1:'Total diário da fonte',declared_daily_total_v1:'Total diário informado'};
const sourceLabel = value=>sourceNames[value] || value || 'Sem fonte';
const methodLabel = value=>methodNames[value] || (value?'Método informado pela fonte':'Sem método');
const blankCheckin = day=>({date:day,fatigue:'',hunger:'',mood:'',pain:'',stress:'',sleep_hours:'',illness:false,notes:''});
const blankMeasure = day=>({date:day,weight_kg:'',waist_cm:'',body_fat_pct:'',lean_mass_kg:'',method:'manual',notes:''});
const blankEnergy = ()=>({total_kcal:'',active_kcal:'',exercise_kcal:'',resting_kcal:'',source:'manual',coverage:'full',coverage_hours:24,method:'daily_total_v1'});
function Section({title,children,description}) {return <section className="panel"><div className="panel-heading"><div><h2>{title}</h2>{description&&<p>{description}</p>}</div></div>{children}</section>;}
function SummaryCard({title,value,note,onClick,action}) {return <section className="panel dashboard-card"><h2>{title}</h2><div className="metric-value">{value}</div><p className="small muted">{note}</p>{onClick&&<button onClick={onClick}>{action}</button>}</section>;}

function EnergyEvidence({energy}) {
  const basis = {modeled_full_day:'Dia completo estimado pelo modelo',source_declared_full:'Dia completo declarado pela fonte',source_partial_or_unknown:'Observação parcial ou cobertura desconhecida'};
  return <><p>{methodLabel(energy.method)} · {sourceLabel(energy.source)}. {basis[energy.coverage_basis] || 'Cobertura ainda não informada'}.</p><div className="evidence-grid">{[['total_kcal','Total diário (kcal)'],['resting_kcal','Repouso (kcal)'],['active_kcal','Atividade (kcal)'],['exercise_kcal','Exercício (kcal)']].map(([key,label])=><p key={key}><span>{label}</span><strong>{format(energy.components?.[key],0)}</strong></p>)}</div><p>Exercícios da mesma fonte já incluídos no total não são somados novamente.</p>{array(energy.alternatives).length>0&&<><h3>Outras referências preservadas</h3><PagedList items={array(energy.alternatives)} label="Referências de gasto">{rows=><div className="table-scroll"><table><thead><tr><th>Origem</th><th>Gasto (kcal)</th><th>Cobertura</th><th>Horas</th></tr></thead><tbody>{rows.map((row,index)=><tr key={row.id || index}><td>{sourceLabel(row.source)}</td><td>{format(row.total_kcal,0)}</td><td>{coverageNames[row.coverage] || 'Desconhecida'}</td><td>{format(row.coverage_hours)}</td></tr>)}</tbody></table></div>}</PagedList><p>São referências alternativas; não compõem uma soma com o gasto selecionado.</p></>}</>;
}

export function CheckinForm({day,model,onSaved,onStateChange}) {
  const existing = array(model.state.checkins).find(row=>row.date === day);
  const [form,setForm] = useState(()=>existing ? {...existing} : blankCheckin(day));
  const [busy,setBusy] = useState(false), [dirty,setDirty] = useState(false), [error,setError] = useState(''), [saved,setSaved] = useState('');
  const lock = useRef(false), draft = useRef(false), selected = useRef(day);
  useEffect(()=>{if(selected.current !== day || !draft.current){setForm(existing ? {...existing} : blankCheckin(day));setSaved('');setDirty(false);draft.current=false;selected.current=day;}},[day,existing?.id,existing?.updated_at]);
  useEffect(()=>{onStateChange?.({busy,dirty});},[busy,dirty,onStateChange]);
  const field = key=>event=>{draft.current=true;setDirty(true);setForm(value=>({...value,[key]:event.target.type==='checkbox'?event.target.checked:event.target.value}));};
  async function submit(event) {
    event.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setError('');
    try {await model.save('checkins',{...form,date:day,...Object.fromEntries(['fatigue','hunger','mood','pain','stress','sleep_hours'].map(key=>[key,optionalNumber(form[key])]))});draft.current=false;setDirty(false);window.dispatchEvent(new Event('ascentiq-personal-changed'));setSaved('Check-in salvo.');onSaved?.();}
    catch(e){setError(e.message);}finally{lock.current=false;setBusy(false);}
  }
  async function remove(){if(lock.current || !window.confirm('Remover o check-in deste dia?'))return;lock.current=true;setBusy(true);setError('');try{await model.save('checkins',existing,true);draft.current=false;setDirty(false);setForm(blankCheckin(day));window.dispatchEvent(new Event('ascentiq-personal-changed'));setSaved('Check-in removido.');onSaved?.();}catch(e){setError(e.message);}finally{lock.current=false;setBusy(false);}}
  return <form className="personal-form" onSubmit={submit}><ErrorNotice error={error}/><StatusNotice message={saved}/><fieldset disabled={busy} className="form-fieldset"><div className="form-grid">{[['fatigue','Fadiga · 0 nenhuma, 10 extrema'],['hunger','Fome · 0 nenhuma, 10 extrema'],['mood','Disposição · 0 baixa, 10 ótima'],['pain','Dor · 0 nenhuma, 10 extrema'],['stress','Estresse · 0 nenhum, 10 extremo']].map(([key,label])=><label key={key}>{label}<input type="number" min="0" max="10" step="1" value={form[key] ?? ''} onChange={field(key)}/></label>)}<label>Sono informado (horas)<input type="number" min="0" max="24" step="0.1" value={form.sleep_hours ?? ''} onChange={field('sleep_hours')}/></label><label className="checkbox-label"><input type="checkbox" checked={Boolean(form.illness)} onChange={field('illness')}/>Estou com sinais de doença</label><label className="wide">Como você está hoje?<textarea rows="3" maxLength="5000" value={form.notes || ''} onChange={field('notes')} placeholder="Contexto que ajude a interpretar o dia"/></label></div></fieldset><div className="report-actions"><button className="primary" disabled={busy || model.loading}>{busy?'Salvando…':existing?'Atualizar check-in':'Salvar check-in'}</button>{existing&&<button type="button" disabled={busy || model.loading} onClick={remove}>Remover check-in</button>}</div><p className="small muted">Campos opcionais. Um campo vazio continua desconhecido.</p></form>;
}

export function Today({data,onNavigate,onAssistant}) {
  const [day,setDay] = useState(today()), model = usePersonal(day,14);
  const [food,setFood] = useState(null), [foodError,setFoodError] = useState(''), [dialog,setDialog] = useState(null);
  const [dialogState,setDialogState] = useState({busy:false,dirty:false});
  const energy = model.summary.energy || {}, activePlan = model.summary.active_plan, goal = model.summary.active_goal;
  const strength = array(data?.strength).filter(row=>row.date===day);
  const linked = new Set(strength.flatMap(row=>array(row.garmin_activity_ids).map(String)));
  const sessions = [...array(data?.activities).filter(row=>row.date===day && !linked.has(String(row.id))),...strength];
  const sleep = array(data?.sleep?.daily).find(row=>row.date===day);
  const checkin = array(model.state.checkins).find(row=>row.date===day);
  const trainingMinutes = sessions.reduce((sum,row)=>sum+Number(row.duration_seconds ?? 0)/60,0);
  const trainingLoad = array(data?.performance?.series).find(row=>row.date===day)?.daily_load;
  const trainingNote = `${trainingLoad!=null?`Carga registrada: ${format(trainingLoad)}.`:'Carga ainda sem dado.'}${trainingMinutes?` ${format(trainingMinutes,0)} minutos com duração disponível.`:''}`;
  useEffect(()=>{const refresh=()=>model.load().catch(()=>{});window.addEventListener('ascentiq-personal-changed',refresh);window.addEventListener('focus',refresh);return()=>{window.removeEventListener('ascentiq-personal-changed',refresh);window.removeEventListener('focus',refresh);};},[model.load]);
  useEffect(()=>{let active=true;setFood(null);setFoodError('');personalApi(`food/${day}`).then(value=>{if(active)setFood(value);}).catch(e=>{if(active)setFoodError(e.message);});return()=>{active=false;};},[day,model.state.revision]);
  const kcalTarget = food?.targets?.kcal ?? activePlan?.target_kcal;
  const proteinTarget = food?.targets?.protein_g ?? activePlan?.protein_g;
  const proteinKnown = food?.fasting_declared || array(food?.entries).some(entry=>array(entry.analysis?.items).some(item=>item.protein_g!=null));
  const caloriesKnown = food?.fasting_declared || array(food?.entries).some(entry=>array(entry.analysis?.items).some(item=>item.kcal!=null));
  const protein = proteinKnown ? food?.totals?.protein_g : null;
  const registered = caloriesKnown ? food?.totals?.kcal ?? energy.registered_kcal : null;
  const open = value=>{setDialogState({busy:false,dirty:false});setDialog(value);};
  const navigate = tab=>onNavigate?.(tab,day);
  return <><PageHeading kicker="SEU DIA" title="Dashboard">Alimentação, treinos e recuperação em uma visão rápida.</PageHeading><div className="filters"><label>Dia<input type="date" value={day} onChange={e=>setDay(e.target.value)}/></label><button disabled={model.loading} onClick={()=>model.load().catch(()=>{})}>Atualizar</button><InfoButton title="Como ler este dia"><p>O total registrado pode ser apenas um subtotal. Um diário parcial ou com calorias pendentes não permite afirmar o déficit do dia.</p><PagedList items={array(energy.limitations)} label="Limitações dos registros">{rows=>rows.map((text,index)=><p key={index}>{text}</p>)}</PagedList><p>Sem atividade registrada não confirma descanso. O sono mantém a data atribuída pela fonte.</p><h3>Referência energética</h3><EnergyEvidence energy={energy}/></InfoButton></div><PersonalLoading model={model}/><ErrorNotice error={foodError}/>
    {model.value&&<><div className="report-actions dashboard-actions"><button className="primary" onClick={()=>open('review')}>Analisar meu dia</button><button onClick={()=>open('checkin')}>{checkin?'Editar check-in':'Registrar check-in'}</button><button onClick={()=>navigate('goals')}>Objetivos</button><button onClick={()=>onAssistant ? onAssistant(day) : navigate('assistant')}>Assistente</button></div>
      <div className="split dashboard-summary"><SummaryCard title="Alimentação" value={<>{format(registered,0)} <small>/ {kcalTarget!=null?format(kcalTarget,0):'Sem meta'} kcal</small></>} note={`${intakeStatus[energy.intake_status] || 'Sem registros'}${energy.pending_count?` · ${energy.pending_count} estimativa(s) pendente(s)`:''}`} onClick={()=>navigate('nutrition')} action="Ver Nutrition"/><SummaryCard title="Proteína" value={<>{format(protein,0)} <small>/ {proteinTarget!=null?format(proteinTarget,0):'Sem meta'} g</small></>} note={proteinKnown?'Total das estimativas disponíveis.':'Ainda sem proteína estimada neste dia.'}/><SummaryCard title="Treino" value={<>{sessions.length} <small>atividade(s)</small></>} note={trainingNote} onClick={()=>navigate('overview')} action="Ver Workouts"/><SummaryCard title="Sono" value={sleep?.duration_minutes!=null?<>{format(sleep.duration_minutes/60,1)} <small>h</small></>:'Sem dado'} note={sleep?`Referência: ${dayLabel(sleep.date)}${sleep.score!=null?` · pontuação ${format(sleep.score,0)}`:''}`:`Nenhum registro para ${dayLabel(day)}.`} onClick={()=>navigate('sleep')} action="Ver Sleep"/></div>
      <div className="split"><Section title="Objetivo principal"><h3>{goal?.description || 'Você ainda não definiu um objetivo.'}</h3><p className="small muted">{activePlan?`Plano ${activePlan.version || 1} · próxima revisão ${dayLabel(activePlan.next_review_date)}`:'Defina um objetivo para acompanhar seu progresso.'}</p><button onClick={()=>navigate('goals')}>Abrir objetivos e plano</button></Section><Section title="Check-in"><p>{checkin?'Seu contexto de recuperação está registrado.':'Sem check-in para este dia.'}</p><p className="small muted">Fadiga, disposição, fome e sono ajudam a interpretar seus registros.</p><button onClick={()=>open('checkin')}>{checkin?'Editar check-in':'Registrar check-in'}</button></Section></div>
      {model.value.nutrition_targets?.status==='missing_data'&&<div className="notice"><strong>Complete seu perfil para calcular a meta</strong><p>{model.value.nutrition_targets.message}</p><button onClick={()=>navigate('profile')}>Perfil e medidas</button></div>}
    <Frequency revision={`${model.state.revision}-${data.generated_at}`}/></>}
    {dialog==='review'&&<Modal title={`Análise do dia · ${dayLabel(day)}`} onClose={()=>setDialog(null)} busy={dialogState.busy} dirty={dialogState.dirty}><DayReview day={day} revision={model.state.revision} onStateChange={setDialogState}/></Modal>}
    {dialog==='checkin'&&<Modal title={`Check-in · ${dayLabel(day)}`} onClose={()=>setDialog(null)} busy={dialogState.busy} dirty={dialogState.dirty}><CheckinForm day={day} model={model} onStateChange={setDialogState} onSaved={()=>setDialog(null)}/></Modal>}
  </>;
}

function EnergyEditor({day,model,onStateChange}) {
  const [record,setRecord] = useState(blankEnergy), [busy,setBusy] = useState(false), [dirty,setDirty] = useState(false), [error,setError] = useState(''), [message,setMessage] = useState('');
  const lock = useRef(false), draft = useRef(false);
  useEffect(()=>{if(draft.current)return;const saved=array(model.state.energy_records).find(row=>row.date===day);setRecord(saved?{...blankEnergy(),...saved,...Object.fromEntries(['total_kcal','active_kcal','exercise_kcal','resting_kcal'].map(key=>[key,saved[key]??'']))}:blankEnergy());},[day,model.state.revision]);
  useEffect(()=>{onStateChange?.({busy,dirty});},[busy,dirty,onStateChange]);
  const input = key=>event=>{draft.current=true;setDirty(true);setRecord(value=>({...value,[key]:event.target.value}));};
  async function save(event){event.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await model.save('energy_records',{...record,date:day,...Object.fromEntries(['total_kcal','active_kcal','exercise_kcal','resting_kcal','coverage_hours'].map(key=>[key,optionalNumber(record[key])]))});draft.current=false;setDirty(false);window.dispatchEvent(new Event('ascentiq-personal-changed'));setMessage('Gasto registrado. O balanço foi recalculado.');}catch(e){setError(e.message);}finally{lock.current=false;setBusy(false);}}
  return <details className="panel"><summary className="section-summary">Registrar uma referência de gasto energético</summary><ErrorNotice error={error}/><StatusNotice message={message}/><p className="small muted">Referência de {dayLabel(day)}. O total diário já inclui os exercícios da fonte.</p><form className="personal-form" onSubmit={save}><fieldset disabled={busy} className="form-fieldset"><div className="form-grid">{[['total_kcal','Total diário (kcal)'],['resting_kcal','Repouso, se conhecido (kcal)'],['active_kcal','Atividade, se conhecida (kcal)'],['exercise_kcal','Exercício, se conhecido (kcal)']].map(([key,label])=><label key={key}>{label}<input type="number" min="0" max="20000" required={key==='total_kcal'} step="1" value={record[key]} onChange={input(key)}/></label>)}<label>Fonte<input value={record.source} required onChange={input('source')}/></label><label>Cobertura<select value={record.coverage} onChange={input('coverage')}><option value="full">Dia completo</option><option value="partial">Parcial</option><option value="unknown">Desconhecida</option></select></label><label>Horas cobertas<input type="number" min="0" max="24" value={record.coverage_hours ?? ''} onChange={input('coverage_hours')}/></label><label>Como o total foi obtido?<input value={record.method || ''} onChange={input('method')}/></label></div></fieldset><button className="primary" disabled={busy || model.loading}>{busy?'Salvando…':'Salvar gasto'}</button></form></details>;
}

export default function Health({Chart,initialDay,onStateChange}) {
  const [day,setDay] = useState(initialDay || today()), model = usePersonal(day,30);
  const [profile,setProfile] = useState({}), [preferences,setPreferences] = useState({}), [measure,setMeasure] = useState(()=>blankMeasure(day));
  const [busy,setBusy] = useState(false), [error,setError] = useState(''), [message,setMessage] = useState('');
  const [profileDirty,setProfileDirty] = useState(false), [preferencesDirty,setPreferencesDirty] = useState(false), [measureDirty,setMeasureDirty] = useState(false);
  const [checkinOpen,setCheckinOpen] = useState(false), [checkinState,setCheckinState] = useState({busy:false,dirty:false}), [energyState,setEnergyState] = useState({busy:false,dirty:false});
  const profileDraft = useRef(false), preferencesDraft = useRef(false), lock = useRef(false);
  const dirty = profileDirty || preferencesDirty || measureDirty || checkinState.dirty || energyState.dirty;
  const saving = busy || checkinState.busy || energyState.busy;
  useEffect(()=>{if(!model.value)return;if(!profileDraft.current)setProfile({...model.summary.profile,...model.state.profile});if(!preferencesDraft.current)setPreferences({...defaults,...model.state.preferences});},[model.state.revision,Boolean(model.value)]);
  useEffect(()=>{onStateChange?.({busy:saving,dirty});},[saving,dirty,onStateChange]);
  const input = (set,key,mark)=>event=>{mark?.();set(value=>({...value,[key]:event.target.value}));};
  const markProfile = ()=>{profileDraft.current=true;setProfileDirty(true);};
  const markPreferences = ()=>{preferencesDraft.current=true;setPreferencesDirty(true);};
  const markMeasure = ()=>setMeasureDirty(true);
  async function commit(kind,value,notice,remove=false) {if(lock.current)return false;lock.current=true;setBusy(true);setError('');setMessage('');try{if(kind==='preferences')value=Object.fromEntries(Object.entries(value).filter(([,v])=>v!==null));await model.save(kind,value,remove);if(kind==='profile'){profileDraft.current=false;setProfileDirty(false);}if(kind==='preferences'){preferencesDraft.current=false;setPreferencesDirty(false);}window.dispatchEvent(new Event('ascentiq-personal-changed'));setMessage(notice);return true;}catch(e){setError(e.message);return false;}finally{lock.current=false;setBusy(false);}}
  function saveProfile(event){event.preventDefault();commit('profile',{...profile,...Object.fromEntries(numeric.map(key=>[key,optionalNumber(profile[key])]))},'Perfil atualizado.');}
  async function saveMeasure(event){event.preventDefault();const saved=await commit('measurements',{...measure,...Object.fromEntries(['weight_kg','waist_cm','body_fat_pct','lean_mass_kg'].map(key=>[key,optionalNumber(measure[key])]))},'Medida salva.');if(saved){setMeasure(blankMeasure(day));setMeasureDirty(false);}}
  function editMeasure(row){if(measureDirty && !window.confirm('Descartar a medida não salva para editar este registro?'))return;setMeasure({...row,...Object.fromEntries(['weight_kg','waist_cm','body_fat_pct','lean_mass_kg'].map(key=>[key,row[key]??'']))});setMeasureDirty(false);}
  const measures = array(model.state.measurements).slice().sort((a,b)=>b.date.localeCompare(a.date));
  return <><PageHeading kicker="PERFIL / MEDIDAS" title="Suas referências pessoais">Mantenha o peso, o perfil e suas preferências atualizados.</PageHeading><PersonalLoading model={model}/><ErrorNotice error={error}/><StatusNotice message={message}/>{model.value&&<>
    <Section title="Perfil pessoal" description="Informações necessárias para os cálculos."><form className="personal-form" onSubmit={saveProfile}><fieldset disabled={saving} className="form-fieldset"><div className="form-grid"><label>Nome<input required maxLength="120" value={profile.name || ''} onChange={input(setProfile,'name',markProfile)}/></label><label>Data de nascimento<input type="date" value={profile.birth_date || ''} onChange={input(setProfile,'birth_date',markProfile)}/></label><label>Altura (cm)<input type="number" min="50" max="260" step="0.1" value={profile.height_cm ?? ''} onChange={input(setProfile,'height_cm',markProfile)}/></label><label>Peso de referência (kg)<input type="number" min="20" max="500" step="0.1" value={profile.weight_kg ?? ''} onChange={input(setProfile,'weight_kg',markProfile)}/></label><label>Sexo usado na fórmula de gasto<select value={profile.sex || ''} onChange={input(setProfile,'sex',markProfile)}><option value="">Não informado</option><option value="male">Masculino</option><option value="female">Feminino</option></select></label><label>Gasto diário de referência, se informado (kcal)<input type="number" min="500" max="10000" value={profile.manual_tdee_kcal ?? ''} onChange={input(setProfile,'manual_tdee_kcal',markProfile)}/></label><label>Fuso horário<input value={profile.timezone || 'America/Sao_Paulo'} onChange={input(setProfile,'timezone',markProfile)}/></label></div></fieldset><button className="primary" disabled={saving || model.loading}>Salvar perfil</button></form></Section>
    <details className="panel"><summary className="section-summary">Preferências e acompanhamento</summary><form className="personal-form" onSubmit={event=>{event.preventDefault();commit('preferences',{...preferences,...Object.fromEntries(['activity_factor','review_days','review_frequency_days','min_complete_days','min_weight_measurements','adjustment_kcal'].map(key=>[key,optionalNumber(preferences[key])]))},'Preferências atualizadas.');}}><fieldset disabled={saving} className="form-fieldset"><div className="form-grid"><label>Referência preferida para o gasto<select value={preferences.energy_method || 'auto'} onChange={input(setPreferences,'energy_method',markPreferences)}><option value="auto">Automático · total completo ou modelo</option><option value="model">Modelo a partir do perfil</option><option value="wearable">Somente relógio ou plataforma</option></select></label><label>Fator de atividade para gasto modelado<select value={preferences.activity_factor ?? ''} onChange={input(setPreferences,'activity_factor',markPreferences)}><option value="">Não informado</option><option value="1.2">1,20 · rotina sedentária</option><option value="1.375">1,375 · atividade leve</option><option value="1.55">1,55 · atividade moderada</option><option value="1.725">1,725 · atividade intensa</option><option value="1.9">1,90 · atividade muito intensa</option></select></label>{[['review_frequency_days','Intervalo entre revisões (dias)',1,90,7],['review_days','Janela de evidência (dias)',7,90,14],['min_complete_days','Dias completos exigidos',1,90,10],['min_weight_measurements','Medidas de peso exigidas',4,90,4],['adjustment_kcal','Passo de ajuste energético (kcal)',25,200,100]].map(([key,label,min,max,fallback])=><label key={key}>{label}<input type="number" min={min} max={max} value={preferences[key] ?? fallback} onChange={input(setPreferences,key,markPreferences)}/></label>)}{[['modalities','Modalidades e rotina'],['food_preferences','Preferências alimentares'],['allergies','Alergias declaradas'],['restrictions','Restrições e orientações registradas']].map(([key,label])=><label className="wide" key={key}>{label}<textarea rows="2" maxLength="5000" value={Array.isArray(preferences[key])?preferences[key].join(', '):preferences[key] || ''} onChange={input(setPreferences,key,markPreferences)}/></label>)}</div><p className="small muted">As fontes são alternativas e não são somadas. O fator de atividade já inclui a atividade habitual.</p><label className="checkbox-label"><input type="checkbox" checked={preferences.review_reminders !== false} onChange={e=>{markPreferences();setPreferences(value=>({...value,review_reminders:e.target.checked}));}}/>Lembrar as revisões do plano</label></fieldset><button className="primary" disabled={saving || model.loading}>Salvar preferências</button></form></details>
    <Section title={measure.id?'Editar medida corporal':'Nova medida corporal'} description="Registre a data e o método da medição."><form className="personal-form" onSubmit={saveMeasure}><fieldset disabled={saving} className="form-fieldset"><div className="form-grid"><label>Data<input type="date" required value={measure.date} onChange={input(setMeasure,'date',markMeasure)}/></label><label>Método<input maxLength="200" value={measure.method} onChange={input(setMeasure,'method',markMeasure)} placeholder="Balança, bioimpedância, antropometria…"/></label>{[['weight_kg','Peso (kg)',500],['waist_cm','Cintura (cm)',300],['body_fat_pct','Gordura corporal (%)',100],['lean_mass_kg','Massa magra (kg)',500]].map(([key,label,max])=><label key={key}>{label}<input type="number" min="0" max={max} step="0.1" value={measure[key]} onChange={input(setMeasure,key,markMeasure)}/></label>)}<label className="wide">Notas<textarea rows="2" value={measure.notes || ''} onChange={input(setMeasure,'notes',markMeasure)}/></label></div></fieldset><div className="report-actions"><button className="primary" disabled={saving || model.loading}>Salvar medida</button>{measure.id&&<button type="button" disabled={saving} onClick={()=>{if(!measureDirty || window.confirm('Descartar as alterações desta medida?')){setMeasure(blankMeasure(day));setMeasureDirty(false);}}}>Cancelar edição</button>}</div></form><PagedList items={measures} label="Medidas corporais">{rows=><div className="record-list">{rows.map(row=><div className="record-row" key={row.id}><div><strong>{dayLabel(row.date)}</strong><p>{[['weight_kg','kg'],['waist_cm','cm cintura'],['body_fat_pct','% gordura'],['lean_mass_kg','kg massa magra']].filter(([key])=>row[key]!=null).map(([key,unit])=>`${format(row[key])} ${unit}`).join(' · ') || 'Sem valores'}<span className="small muted block">{row.method || 'Método não informado'}{row.notes?' · '+row.notes:''}</span></p></div><div className="report-actions"><button type="button" disabled={saving} onClick={()=>editMeasure(row)}>Editar</button><button type="button" disabled={saving || model.loading} onClick={async()=>{if(!window.confirm('Remover esta medida corporal?'))return;await commit('measurements',row,'Medida removida.',true);}}>Remover</button></div></div>)}{!measures.length&&<p className="empty">Nenhuma medida pessoal registrada.</p>}</div>}</PagedList></Section>
    <Section title="Contexto do dia"><div className="filters"><label>Dia<input type="date" disabled={saving || dirty} value={day} onChange={e=>{setEnergyState({busy:false,dirty:false});setDay(e.target.value);}}/></label><button disabled={saving} onClick={()=>{setCheckinState({busy:false,dirty:false});setCheckinOpen(true);}}>Registrar ou editar check-in</button></div></Section>
    <EnergyEditor key={day} day={day} model={model} onStateChange={setEnergyState}/>
    {Chart&&<Section title="Evolução das medidas pessoais"><div className="split"><div><h3>Peso registrado</h3><Chart rows={measures.slice().reverse()} keys={[{key:'weight_kg',label:'Peso (kg)',color:'#3fb950'}]} points height={230}/></div><div><h3>Cintura registrada</h3><Chart rows={measures.slice().reverse()} keys={[{key:'waist_cm',label:'Cintura (cm)',color:'#f78166'}]} points height={230}/></div></div></Section>}
  </>}{checkinOpen&&<Modal title={`Check-in · ${dayLabel(day)}`} onClose={()=>{setCheckinOpen(false);setCheckinState({busy:false,dirty:false});}} busy={checkinState.busy} dirty={checkinState.dirty}><CheckinForm day={day} model={model} onStateChange={setCheckinState} onSaved={()=>{setCheckinOpen(false);setCheckinState({busy:false,dirty:false});}}/></Modal>}</>;
}
