import React, { useEffect, useState, useDeferredValue } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';

const fmt = (n, digits = 1) => n == null ? 'Sem dado' : Number(n).toLocaleString('pt-BR', { maximumFractionDigits: digits });
const date = (v) => v ? new Date(v.slice(0, 10) + 'T12:00:00').toLocaleDateString('pt-BR') : 'Sem registro';
const daysBefore = (v, n) => { const d = new Date(v + 'T12:00:00Z'); d.setUTCDate(d.getUTCDate() - n); return d.toISOString().slice(0, 10); };
const kinds = { running: 'Corrida', strength: 'Força', cycling: 'Bike', swimming: 'Natação', other: 'Outros' };
const colors = { fitness: '#3fb950', fatigue: '#f78166', form: '#d29922', volume: '#3fb950', km: '#3fb950' };
const nav = [['overview', 'Visão geral', '01'], ['running', 'Corrida', '02'], ['strength', 'Força', '03'], ['body', 'Corpo & medidas', '04'], ['medical', 'Exames & saúde', '05'], ['reports', 'Relatórios', '06']];
async function api(path, body) {
  const response = await fetch('/api/' + path, { credentials: 'same-origin', cache: 'no-store', ...(body ? { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-AscentIQ-Request': '1' }, body: JSON.stringify(body) } : {}) });
  if (!response.ok) { const payload = await response.json().catch(() => ({})); const error = new Error(payload.detail || (response.status === 401 ? 'Entre novamente para acessar seus dados.' : 'Não foi possível concluir a solicitação.')); error.status = response.status; throw error; }
  return response.json();
}
function Peak({ small = false }) { return <svg viewBox="0 0 48 44" width={small ? 27 : 43} fill="none" aria-hidden="true"><path d="M3 38 21 5l9 17 5-9 10 25H3Z" stroke="currentColor" strokeWidth="2.3"/><path d="m14 19 7 5 7-6M8 38l13-14 13 14" stroke="currentColor" strokeWidth="1.5"/></svg>; }
function Card({ label, value, unit, note, tone = '' }) { return <div className={'metric ' + tone}><div className="eyebrow">{label}</div><div className="metric-value">{value}<span>{unit}</span></div><div className="muted small">{note}</div></div>; }
function Panel({ title, sub, children, aside, className = '' }) { return <section className={'panel ' + className}><div className="panel-heading"><div><h2>{title}</h2>{sub && <p>{sub}</p>}</div>{aside}</div>{children}</section>; }
function Empty({ children = 'Nenhum registro nesse período.' }) { return <div className="empty">{children}</div>; }

function Chart({ rows, keys: inputKeys, height = 290, numbers = false, zeroBaseline = !inputKeys.some(k => ['weight_kg', 'waist_cm'].includes(k.key)), title = 'Evolução dos dados' }) {
  const keys = inputKeys.map(k => ({...k, color: ({'#16695e':'#3fb950','#bd633e':'#f78166','#a88926':'#d29922'})[k.color] || k.color || colors[k.key]}));
  const [hover, setHover] = useState(null);
  if (!rows.length || !keys.some(k => rows.some(r => r[k.key] != null))) return <Empty/>;
  const w = 1000, h = height, left = 45, right = 18, top = 22, bottom = 38;
  const values = rows.flatMap(r => keys.map(k => r[k.key]).filter(v => v != null).map(Number));
  const rawMin = Math.min(...values), rawMax = Math.max(...values);
  const padding = zeroBaseline ? 0 : Math.max((rawMax-rawMin)*.15, Math.abs(rawMax)*.002, .05);
  const min = zeroBaseline ? Math.min(0,rawMin) : rawMin-padding;
  const max = zeroBaseline ? Math.max(1,rawMax) : rawMax+padding;
  const span = max - min || 1;
  const timestamps = rows.map(row => Date.parse(row.date));
  const firstDate = Math.min(...timestamps), dateSpan = Math.max(...timestamps)-firstDate;
  const x = (i) => left + (dateSpan ? (timestamps[i]-firstDate)/dateSpan : .5) * (w-left-right);
  const y = (v) => h - bottom - (v - min) / span * (h - top - bottom);
  const select = (event) => { const b = event.currentTarget.getBoundingClientRect(); const px = (event.clientX - b.left) / b.width * w; let nearest = 0; rows.forEach((_,i)=>{if(Math.abs(x(i)-px)<Math.abs(x(nearest)-px))nearest=i;});setHover(nearest); };
  return <div className="chart"><div className="legend">{keys.map(k => <span key={k.key}><i style={{ background: k.color || colors[k.key] }}/>{k.label}</span>)}</div><svg role="img" aria-label={title} viewBox={`0 0 ${w} ${h}`} onPointerMove={select} onPointerLeave={() => setHover(null)}>
    {Array.from({ length: 5 }, (_, i) => { const value = min + span * i / 4; return <g key={i}><line x1={left} x2={w-right} y1={y(value)} y2={y(value)} stroke="#e5e4dc" strokeDasharray="4 5"/><text x="3" y={y(value)+4} className="chart-label">{fmt(value, span < 5 ? 2 : span < 20 ? 1 : 0)}</text></g>; })}
    {keys.map(k => { const chunks = []; let current = []; rows.forEach((r, i) => { if (r[k.key] != null) current.push([i,r[k.key]]); else if (current.length) { chunks.push(current); current=[]; } }); if(current.length) chunks.push(current); return <g key={k.key}>{chunks.map((chunk, i) => <polyline key={i} points={chunk.map(([idx,v]) => `${x(idx)},${y(v)}`).join(' ')} fill="none" stroke={k.color || colors[k.key]} strokeWidth="2.7" strokeLinejoin="round" strokeLinecap="round"/>)}{rows.length <= 25 && rows.map((r,i) => r[k.key] != null && <g key={i}><circle cx={x(i)} cy={y(r[k.key])} r="3.4" fill={k.color || colors[k.key]}/>{numbers && <text x={x(i)} y={y(r[k.key])-9} textAnchor="middle" fill={k.color || colors[k.key]} fontSize="11">{fmt(r[k.key])}</text>}</g>)}</g>; })}
    {[...new Set([0, Math.floor((rows.length-1)/2), rows.length-1])].map((i,index) => <text key={i} x={x(i)} y={h-9} textAnchor={i===0?'start':i===rows.length-1?'end':'middle'} className="chart-label">{date(rows[i].date)}</text>)}
    {hover != null && <g><line x1={x(hover)} x2={x(hover)} y1={top} y2={h-bottom} stroke="#20372d" opacity=".25"/>{keys.map(k => rows[hover][k.key] != null && <circle key={k.key} cx={x(hover)} cy={y(rows[hover][k.key])} r="5" fill={k.color || colors[k.key]} stroke="#fff" strokeWidth="2"/>)}</g>}
  </svg><div className="chart-readout" aria-live="polite">{hover != null ? <><b>{date(rows[hover].date)}</b>{keys.map(k => <span key={k.key}>{k.label}: <strong>{fmt(rows[hover][k.key])}</strong></span>)}</> : 'Passe sobre o gráfico para consultar os valores por dia.'}</div></div>;
}
function Performance({ data }) {
  const [range,setRange] = useState(21), [numbers,setNumbers] = useState(false);
  const rows = data.performance.series.slice(-range);
  return <Panel title="Carga, adaptação e equilíbrio" sub="Seu modelo de Fitness, Fadiga e Forma. Uma leitura de carga, não um diagnóstico." aside={<div className="chart-controls"><select aria-label="Período do gráfico" value={range} onChange={e=>setRange(Number(e.target.value))}><option value={21}>3 semanas</option><option value={90}>90 dias</option><option value={180}>6 meses</option><option value={1500}>Todo o histórico</option></select><label className="check"><input type="checkbox" checked={numbers} onChange={e=>setNumbers(e.target.checked)}/>Valores</label></div>}><Chart rows={rows} keys={[{key:'fitness',label:'Fitness'},{key:'fatigue',label:'Fadiga'},{key:'form',label:'Forma'}]} numbers={numbers}/><details className="method"><summary>Como ler esses números</summary><p>Fitness = carga crônica suavizada em 42 dias. Fadiga = carga aguda em 7 dias. Forma = Fitness menos Fadiga. A carga combina FC, duração, modalidade, D+ e componente muscular Hevy. Não é TSS oficial, VO₂max nem percentual de condicionamento.</p><div className="table-scroll"><table><thead><tr><th>Data</th><th>Fitness</th><th>Fadiga</th><th>Forma</th><th>Carga</th></tr></thead><tbody>{rows.slice(-21).map(r=><tr key={r.date}><td>{date(r.date)}</td><td>{fmt(r.fitness)}</td><td>{fmt(r.fatigue)}</td><td>{fmt(r.form)}</td><td>{fmt(r.daily_load)}</td></tr>)}</tbody></table></div></details></Panel>;
}
function ActivityTable({ rows }) { const [count,setCount] = useState(20); return rows.length ? <><div className="table-scroll"><table><thead><tr><th>Data / atividade</th><th>Modalidade</th><th>Distância</th><th>Tempo</th><th>FC média</th><th>D+</th></tr></thead><tbody>{rows.slice(0,count).map((r,i)=><tr key={r.id+'-'+i}><td><strong>{r.name}</strong><span className="small muted block">{date(r.date)}</span></td><td><span className={'tag '+r.kind}>{kinds[r.kind]}</span></td><td>{r.distance_km != null ? fmt(r.distance_km,2)+' km' : 'Sem dado'}</td><td>{r.elapsed_time || 'Sem dado'}</td><td>{r.avg_hr == null ? 'Sem dado' : r.avg_hr+' bpm'}</td><td>{r.elevation_gain_m == null ? 'Sem dado' : fmt(r.elevation_gain_m,0)+' m'}{r.elevation_source==='official' && <span className="small block muted">Oficial</span>}</td></tr>)}</tbody></table></div>{rows.length>count && <button className="text-button" onClick={()=>setCount(count+30)}>Mostrar mais ({rows.length-count})</button>}</> : <Empty/>; }
function Filter({ from, to, setFrom, setTo, search, setSearch }) { return <div className="filters"><label>De<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Até<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><label className="search">Buscar<input type="search" value={search} placeholder="Nome da atividade ou exercício" onChange={e=>setSearch(e.target.value)}/></label></div>; }
function Overview({ data }) {
  const s=data.performance.summary, week=data.week, body=data.body.current || {};
  return <>
  <div className="metrics three"><Card label="Fitness" value={fmt(s.fitness)} note="Carga crônica · 42 dias" tone="green"/><Card label="Fadiga" value={fmt(s.fatigue)} note="Carga aguda · 7 dias" tone="rust"/><Card label="Forma" value={(s.form>0?'+':'')+fmt(s.form)} note="Fitness − Fadiga · índice estimado" tone="gold"/></div><Performance data={data}/>
  <div className="split"><Panel title="Sua semana em movimento" sub={`${date(week.start)} a ${date(week.end)} · últimos 7 dias`}><div className="week-stats"><div><b>{fmt(week.running_km,2)}</b><span>km de corrida</span></div><div><b>{week.strength_sessions}</b><span>sessões de força</span></div><div><b>{week.working_sets}</b><span>séries de trabalho</span></div><div><b>{fmt(week.running_elevation_m,0)}</b><span>metros D+ corrida</span></div></div><div className="mix">{Object.entries(week.by_kind).map(([k,n])=><div key={k}><span>{kinds[k]}</span><div className="mix-bar"><i style={{width: (n/Math.max(1,week.activity_count)*100)+'%'}}/></div><b>{n}</b></div>)}</div></Panel><Panel title="Corpo & recuperação" sub="Referências com data, sem inferir medidas atuais"><div className="reference"><span>Avaliação corporal · {date(data.body.reference_date)}</span><b>{fmt(body.body_fat_pct,2)}<small>% gordura</small></b><div>{fmt(body.weight_kg)} kg · {fmt(body.lean_mass_kg,2)} kg de massa magra</div></div><div className="notice"><b>Sono / recuperação</b><p>{s.recovery?.score == null ? 'Sem pontuação atual de sono. Não é possível confirmar a recuperação por esse dado.' : `Pontuação registrada: ${fmt(s.recovery.score)} (${s.recovery.status}).`}</p><span className="small">Último score: {date(data.freshness.sleep_score)}</span></div></Panel></div>
  <Panel title="Atividades mais recentes" sub="Garmin para o esforço cardiovascular. Hevy para séries e exercícios."><ActivityTable rows={data.activities.slice(0,8)}/></Panel><div className="footnote">Base privada · {data.activities.length} atividades · {data.strength.length} sessões de força consolidadas · Sem LLM nos cálculos</div></>;
}
function Running({ data }) {
  const [from,setFrom]=useState(daysBefore(data.as_of,90)),[to,setTo]=useState(data.as_of),[search,setSearch]=useState(''); const query=useDeferredValue(search.toLowerCase());
  const rows=data.activities.filter(r=>r.kind==='running'&&r.date>=from&&r.date<=to&&r.name?.toLowerCase().includes(query));
  const total=rows.reduce((a,r)=>({km:a.km+(r.distance_km||0),seconds:a.seconds+(r.duration_seconds||0),d:a.d+(r.elevation_gain_m||0)}),{km:0,seconds:0,d:0});
  const weeks={}; rows.forEach(r=>{const d=new Date(r.date+'T12:00:00Z'); const offset=(d.getUTCDay()+6)%7; const key=daysBefore(r.date,offset); weeks[key]=(weeks[key]||0)+(r.distance_km||0);});
  const chart=Object.entries(weeks).sort().map(([date,km])=>({date,km}));
  const races=data.race_index.entries || [];
  return <><PageTitle kicker="ENDURANCE / TERRENO / ESFORÇO" title="Corrida, com contexto." text="A distância conta. O terreno e a continuidade contam também."/><Filter {...{from,to,setFrom,setTo,search,setSearch}}/><div className="metrics three"><Card label="Distância no período" value={fmt(total.km,2)} unit="km" note={`${rows.length} atividades`}/><Card label="Tempo em atividade" value={fmt(total.seconds/3600)} unit="h" note="Duração total registrada"/><Card label="Subida acumulada" value={fmt(total.d,0)} unit="m" note="GPX oficial quando vinculado; relógio nos demais"/></div><Panel title="Volume semanal de corrida" sub="Distância registrada por semana; semanas sem registros não são interpoladas."><Chart rows={chart} keys={[{key:'km',label:'km / semana'}]}/></Panel><Panel title="Histórico de corridas"><ActivityTable rows={rows}/></Panel>{races.length>0 && <Panel title="Execução nas provas / IEP-100" sub={`Benchmark histórico, não prontidão atual. Índice calculado em ${date(data.race_index.generated_at)}.`}><Chart rows={races} keys={[{key:'performance_execution_index',label:'IEP / 100',color:'#a88926'}]} numbers/><div className="table-scroll"><table><thead><tr><th>Prova</th><th>Data</th><th>Tempo</th><th>IEP</th><th>Confiança</th></tr></thead><tbody>{races.map((r,i)=><tr key={i}><td>{r.name}</td><td>{date(r.date)}</td><td>{r.elapsed_time}</td><td>{fmt(r.performance_execution_index)}</td><td>{r.confidence}</td></tr>)}</tbody></table></div></Panel>}</>;
}
function Strength({ data }) {
  const [from,setFrom]=useState(daysBefore(data.as_of,90)),[to,setTo]=useState(data.as_of),[search,setSearch]=useState(''),[exercise,setExercise]=useState(''); const query=useDeferredValue(search.toLowerCase());
  const rows=data.strength.filter(r=>r.date>=from&&r.date<=to&&(`${r.title} ${r.exercises.map(x=>x.name).join(' ')}`).toLowerCase().includes(query));
  const names=[...new Set(rows.flatMap(r=>r.exercises.map(e=>e.name)))].sort(); const selected=exercise || names[0];
  const history=rows.flatMap(r=>r.exercises.filter(e=>e.name===selected).map(e=>({date:r.date,weight:e.max_weight_kg,volume:e.volume_kg}))).reverse();
  const sum=k=>rows.reduce((a,r)=>a+(r[k]||0),0);
  return <><PageTitle kicker="FORÇA / PROGRESSÃO / CONSISTÊNCIA" title="Mais do que levantar peso." text="Séries e cargas do Hevy, conectadas ao contexto cardiovascular do Garmin."/><Filter {...{from,to,setFrom,setTo,search,setSearch}}/><div className="metrics three"><Card label="Sessões de força" value={rows.length} note="Cada sessão consolidada conta uma vez"/><Card label="Séries de trabalho" value={sum('working_sets')} note="Aquecimentos excluídos quando identificados"/><Card label="Volume registrado" value={fmt(sum('volume_kg'),0)} unit="kg·rep" note="Comparar preferencialmente o mesmo exercício"/></div><Panel title="Evolução por exercício" sub="Carga máxima registrada na sessão; não equivale a 1RM." aside={<select aria-label="Exercício" value={selected || ''} onChange={e=>setExercise(e.target.value)}>{names.map(n=><option key={n}>{n}</option>)}</select>}><Chart rows={history} keys={[{key:'weight',label:'Carga máxima / kg',color:'#16695e'}]}/></Panel><Panel title="Diário de musculação" sub={`${rows.length} sessões no período · detalhes completos por exercício`}>{rows.length ? rows.map((r,i)=><details className="session" key={r.id+'-'+i}><summary><div><strong>{r.title}</strong><span>{date(r.date)} · {r.duration || 'Sem duração'} · {r.match_status==='matched' ? 'Garmin + Hevy' : r.exercises.length ? 'Hevy' : 'Garmin / sem séries'}</span></div><div className="session-stats">{fmt(r.volume_kg,0)} <small>kg·rep</small><b>{r.working_sets == null ? 'Sem dado' : r.working_sets+' séries'}</b></div></summary>{r.exercises.length ? r.exercises.map((e,j)=><div className="exercise" key={j}><h3>{e.name}</h3><div className="table-scroll"><table><thead><tr><th>Série</th><th>Tipo</th><th>Carga / kg</th><th>Repetições</th><th>RPE</th></tr></thead><tbody>{e.sets.map((s,k)=><tr key={k}><td>{k+1}</td><td>{s.set_type==='warmup'?'Aquecimento':s.set_type==='normal'?'Trabalho':s.set_type}</td><td>{fmt(s.weight_kg)}</td><td>{s.reps ?? 'Sem dado'}</td><td>{s.rpe ?? 'Sem dado'}</td></tr>)}</tbody></table></div></div>) : <Empty>Esta sessão tem contexto Garmin, mas não há séries correspondentes do Hevy.</Empty>}</details>) : <Empty/>}</Panel></>;
}
const bodyLabels={chest:'Tórax',right_arm:'Braço direito',left_arm:'Braço esquerdo',right_forearm:'Antebraço direito',left_forearm:'Antebraço esquerdo',right_wrist:'Punho direito',left_wrist:'Punho esquerdo',abdomen:'Abdômen',waist:'Cintura',hip:'Quadril',right_thigh:'Coxa direita',left_thigh:'Coxa esquerda',right_calf:'Panturrilha direita',left_calf:'Panturrilha esquerda',axillary:'Axilar',triceps:'Tríceps',subscapular:'Subescapular',abdominal:'Abdominal',suprailiac:'Suprailíaca',thigh:'Coxa',total:'Soma'};
function Body({ data }) { const b=data.body.current||{}, history=data.body.history||[], target=data.nutrition.initial_nutrition_target||{}; return <><PageTitle kicker="COMPOSIÇÃO / MEDIDAS / REFERÊNCIAS" title="O corpo também tem história." text={`Última avaliação: ${date(data.body.reference_date)}. Sem extrapolar medidas para hoje.`}/><div className="metrics four"><Card label="Peso medido" value={fmt(b.weight_kg)} unit="kg" note={date(data.body.reference_date)}/><Card label="Gordura corporal" value={fmt(b.body_fat_pct,2)} unit="%" note="Avaliação antropométrica"/><Card label="Massa magra" value={fmt(b.lean_mass_kg,2)} unit="kg" note="Referência de preservação"/><Card label="Cintura" value={fmt(b.waist_cm)} unit="cm" note="Não confundir com medida abdominal"/></div><div className="split"><Panel title="Peso ao longo do tempo" sub="Somente pontos medidos"><Chart rows={history} keys={[{key:'weight_kg',label:'Peso / kg',color:'#16695e'}]} numbers height={220}/></Panel><Panel title="Cintura ao longo do tempo" sub="Verificar consistência do protocolo de medição"><Chart rows={history} keys={[{key:'waist_cm',label:'Cintura / cm',color:'#bd633e'}]} numbers height={220}/></Panel></div><div className="split"><Panel title="Perimetria" sub={`Centímetros · avaliação de ${date(data.body.reference_date)}`}><div className="measure-grid">{Object.entries(data.body.perimetry_current_cm||{}).map(([k,v])=><div key={k}><span>{bodyLabels[k]||k}</span><b>{fmt(v)} <small>cm</small></b></div>)}</div></Panel><Panel title="Dobras cutâneas" sub="Milímetros · valores medidos no mesmo protocolo"><div className="measure-grid">{Object.entries(data.body.skinfolds_current_mm||{}).map(([k,v])=><div key={k}><span>{bodyLabels[k]||k}</span><b>{fmt(v)} <small>mm</small></b></div>)}</div></Panel></div><Panel title="Nutrição de referência" sub={`Alvos previamente registrados em ${date(data.nutrition.generated_at)}. Não é uma nova prescrição.`}><div className="week-stats"><div><b>{fmt(target.average_kcal_day,0)}</b><span>kcal / dia</span></div><div><b>{target.protein_g_day ?? 'Sem dado'} g</b><span>proteína</span></div><div><b>{target.carbohydrate_g_day ?? 'Sem dado'} g</b><span>carboidrato</span></div><div><b>{target.fat_g_day ?? 'Sem dado'} g</b><span>gordura</span></div></div><p className="muted">{data.body.active_goal?.notes}</p></Panel></>; }
function Medical({ data }) { const m=data.medical; const [query,setQuery]=useState(''); const search=useDeferredValue(query.toLowerCase()); const clearance=m.status.sports_clearance||{}; return <><PageTitle kicker="SAÚDE / DOCUMENTOS / CONTEXTO" title="Exames, sem perder o contexto." text={m.disclaimer}/><div className="medical-intro"><div><span className="eyebrow">ATESTADO REGISTRADO</span><h2>{clearance.status==='cleared'?'Aptidão física documentada':'Sem atestado registrado'}</h2><p>{date(clearance.date)} · {clearance.scope}</p></div><span className="tag">Arquivo médico privado</span></div><Panel title="Resumo já registrado" sub={`Base médica atualizada em ${date(m.updated_at)}`}><p>{m.status.cardiovascular_summary}</p><div className="notice"><b>Contexto da coleta · {date(m.context.laboratory_collection_date)}</b><p>{m.context.athlete_report}</p><p className="small">{m.context.interpretive_relevance}</p></div>{m.status.active_follow_up?.length>0 && <><h3>Acompanhamentos anotados na base</h3><ul>{m.status.active_follow_up.map((x,i)=><li key={i}>{x}</li>)}</ul></>}</Panel><Panel title="Documentos e resultados" sub="Conclusões e observações abaixo são as já armazenadas, não uma nova avaliação médica."><label className="search block">Buscar exame ou indicador<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ex.: glicose, TSH, HDL, Holter"/></label>{m.records.filter(r=>(r.label+' '+r.rows.map(x=>x.label+' '+x.value).join(' ')).toLowerCase().includes(search)).map((r,i)=><details className="session medical-record" key={i} open={search ? true : undefined}><summary><div><strong>{r.label}</strong><span>{date(r.date)} · {r.rows.length} resultados e observações</span></div><span className="tag">Consultar</span></summary><div className="document-links">{r.documents.map(d=><a key={d.id} href={'/api/medical/documents/'+d.id} target="_blank" rel="noreferrer">Documento original ↗</a>)}</div><div className="table-scroll"><table><thead><tr><th>Indicador / contexto</th><th>Resultado registrado</th></tr></thead><tbody>{r.rows.filter(x=>!search || (x.label+' '+x.value).toLowerCase().includes(search) || r.label.toLowerCase().includes(search)).map((x,j)=><tr key={j}><td>{x.label}</td><td>{x.value}</td></tr>)}</tbody></table></div>{Object.entries(r.trends||{}).map(([key,rows])=><Panel key={key} title={key.replaceAll('_',' ')} sub="Histórico transcrito do laudo"><Chart rows={rows} keys={[{key:'value',label:'Resultado',color:'#16695e'}]} height={210} numbers/></Panel>)}</details>)}</Panel>{data.physiology.map((test,i)=><Panel key={i} title="Teste de esforço / referência fisiológica" sub="Valores disponíveis na extração do documento"><p>FC de pico no teste: <strong>{test.peak_hr_bpm} bpm</strong>. Isso não substitui a FC máxima adotada no modelo.</p><div className="notice">{test.notes?.map((n,j)=><p key={j}>{n}</p>)}</div></Panel>)}</>; }
function PageTitle({ kicker,title,text }) { return <div className="page-title"><div className="eyebrow">{kicker}</div><h1>{title}</h1><p>{text}</p></div>; }
function ReportLinks({ report }) { return report ? <div className="report-links"><a className="button" href={'/api/reports/'+report.id+'/html'} target="_blank" rel="noreferrer">Dashboard Typst HTML ↗</a><a className="button download" href={'/api/reports/'+report.id+'/pdf'} download>Baixar PDF</a></div> : null; }
function Reports({ reports,jobs,onJob,busy }) { return <><PageTitle kicker="AUTOMAÇÃO / TYPST / RASTREABILIDADE" title="Uma fotografia de cada semana." text="Relatórios reproduzíveis, com a versão do modelo e a data de cada fonte."/><Panel title="Geração de relatórios" sub={jobs.schedule}><div className="report-actions"><button className="primary" disabled={busy} onClick={()=>onJob('sync')}>Atualizar treinos e gerar</button><button disabled={busy} onClick={()=>onJob('generate')}>Gerar com a base atual</button></div><p className="small muted">O agendamento roda enquanto o Docker estiver ligado. Apenas uma atualização é executada por vez.</p></Panel><Panel title="Histórico de execução">{jobs.jobs?.length ? <div className="table-scroll"><table><thead><tr><th>Início</th><th>Modo</th><th>Estado</th><th>Etapa / resultado</th></tr></thead><tbody>{jobs.jobs.map(j=><tr key={j.id}><td>{new Date(j.created_at).toLocaleString('pt-BR')}</td><td>{j.mode==='sync'?'Atualização + PDF':'Base atual + PDF'}</td><td><span className={'tag '+j.status}>{({queued:'Na fila',running:'Em execução',completed:'Concluído',partial:'Parcial',failed:'Falhou'})[j.status]}</span></td><td>{j.message}{JSON.parse(j.warnings||'[]').map((w,i)=><p key={i} className="small">{w}</p>)}</td></tr>)}</tbody></table></div>:<Empty/>}</Panel><Panel title="Arquivo de relatórios" sub="PDFs gerados localmente com Typst, sem enviar dados ao typst.app">{reports.length?reports.map(r=><div className="report-row" key={r.id}><div><strong>Relatório · {date(r.as_of)}</strong><span className="muted small block">{new Date(r.generated_at).toLocaleString('pt-BR')} · {r.model_version}{r.warnings?.length?' · Fontes parciais':''}</span></div><a className="button" href={'/api/reports/'+r.id+'/pdf'} target="_blank" rel="noreferrer">Abrir PDF ↗</a></div>):<Empty>O primeiro relatório está sendo preparado.</Empty>}</Panel></>; }
function Login({ onLogin }) { const [username,setUsername]=useState('athlete'),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false); async function submit(e){e.preventDefault();setBusy(true);setError('');try{await api('auth/login',{username,password});setPassword('');onLogin();}catch(e){setError(e.message);}finally{setBusy(false);}} return <div className="login-page"><div className="login-story"><div className="brand"><Peak/><span>AscentIQ<small>ATHLETE INTELLIGENCE</small></span></div><h1>Seu histórico.<br/>Sua evolução.<br/><em>Seu próximo cume.</em></h1><p>Treino, performance e saúde.<br/>Uma base privada. Uma visão completa.</p><div className="login-line">GARMIN + HEVY + DADOS DO ATLETA</div></div><form className="login-card" onSubmit={submit}><div className="eyebrow">ACESSO PRIVADO</div><h2>Entre no seu painel.</h2><p>Os dados de treino e saúde ficam no seu próprio ambiente.</p><label>Usuário<input autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} required/></label><label>Senha<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<div className="error" role="alert">{error}</div>}<button className="primary" disabled={busy}>{busy?'Entrando…':'Acessar dashboard'}</button><div className="small muted">Primeiro acesso: credenciais no arquivo local <code>runtime/dashboard/access.txt</code>.</div></form></div>; }
function App() {
  const [authenticated,setAuthenticated]=useState(null),[data,setData]=useState(null),[tab,setTab]=useState('overview'),[reports,setReports]=useState([]),[jobs,setJobs]=useState({jobs:[]}),[error,setError]=useState('');
  const busy=jobs.jobs.some(j=>['queued','running'].includes(j.status));
  async function refresh(){try{const [d,r,j]=await Promise.all([api('dashboard'),api('reports'),api('jobs')]);setData(d);setReports(r.reports);setJobs(j);setError('');}catch(e){if(e.status===401){setAuthenticated(false);setData(null);}else setError(e.message);}}
  useEffect(()=>{api('auth/session').then(()=>setAuthenticated(true)).catch(()=>setAuthenticated(false));if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});},[]);
  useEffect(()=>{if(!authenticated)return;refresh();const timer=setInterval(refresh,5000);return()=>clearInterval(timer);},[authenticated]);
  async function onJob(mode){try{await api('jobs',{mode});await refresh();}catch(e){setError(e.message);}}
  async function logout(){try{await api('auth/logout',{});setAuthenticated(false);setData(null);setReports([]);}catch(e){setError(e.message);}}
  if(authenticated===null)return <div className="loading">Carregando AscentIQ…</div>;
  if(!authenticated)return <Login onLogin={()=>setAuthenticated(true)}/>;
  if(!data)return <div className="loading">{error || 'Preparando seu histórico…'}{error&&<button onClick={refresh}>Tentar novamente</button>}</div>;
  const active=jobs.jobs.find(j=>['queued','running'].includes(j.status));
  return <div className="app">
    <aside className="sidebar">
      <div className="brand"><Peak/><span>AscentIQ<small>ATHLETE INTELLIGENCE</small></span></div>
      <div className="sidebar-label">SEU PAINEL</div>
      <nav>{nav.map(([id,label,n])=><button key={id} className={tab===id?'active':''} onClick={()=>{setTab(id);window.scrollTo({top:0,behavior:'smooth'});}}><span>{n}</span>{label}</button>)}</nav>
      <div className="sidebar-bottom"><div className="avatar">{(data.athlete.name || 'Atleta').split(' ').filter(Boolean).slice(0,2).map(part=>part[0]).join('')}</div><strong>{data.athlete.name}</strong><span>Endurance & alta montanha</span><button onClick={logout}>Sair do painel</button><div className="privacy">Dados privados · ambiente local</div></div>
    </aside>
    <main>
      <header className="topbar"><span>ATLETA / <strong>{nav.find(n=>n[0]===tab)?.[1].toUpperCase()}</strong></span><div><span className="sync-date"><i/>Base de treinos: {date(data.freshness.activities)}</span><button className="primary" disabled={busy} onClick={()=>onJob('sync')}>{busy?'Atualizando…':'Atualizar treinos'}</button></div></header>
      <div className="content">
        {error&&<div className="error" role="alert">{error}<button onClick={()=>setError('')}>Fechar</button></div>}
        {active&&<div className="job-banner" role="status"><span className="spinner"/>{active.message}. Você pode continuar consultando a última versão.</div>}
        {data.sync_warnings?.length>0&&<div className="notice">Atualização parcial: {data.sync_warnings.join(' ')}</div>}
        <ReportLinks report={reports[0]}/>
        <p className="small muted">O PDF inclui somente treinos e carga de treinamento. Medidas corporais e exames ficam apenas no dashboard HTML privado.</p>
        <p className="small muted">Base de carga: Garmin/Strava com detalhes Hevy vinculados. O diário de força inclui também sessões somente do Hevy, que não são automaticamente somadas ao modelo nem à distribuição de atividades.</p>
        {tab==='overview'&&<Overview data={data}/>}
        {tab==='running'&&<Running data={data}/>}
        {tab==='strength'&&<Strength data={data}/>}
        {tab==='body'&&<Body data={data}/>}
        {tab==='medical'&&<Medical data={data}/>}
        {tab==='reports'&&<Reports {...{reports,jobs,onJob,busy}}/>}
        <footer>ASCENTIQ <span>Fonte de verdade: seus registros. Cálculos locais. Dados de saúde privados.</span><span>Snapshot: {new Date(data.generated_at).toLocaleString('pt-BR')}</span></footer>
      </div>
    </main>
  </div>;
}
createRoot(document.getElementById('root')).render(<App/>);
