import React, { useEffect, useState, useDeferredValue } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';
import DailyAnalysis from './DailyAnalysis';
import SleepContext from './SleepContext';
import Sleep from './Sleep';
import Nutrition from './Nutrition';
import Health, {Today} from './Health';
import Goals from './Goals';
import Assistant from './Assistant';
import Settings from './Settings';
import Documents from './Documents';
import InstallApp from './InstallApp';
import Planning from './Planning';
import {Modal,PagedList,InfoButton} from './ui';
import {today} from './personalApi';

const fmt = (n, digits = 1) => n == null ? 'Sem dado' : Number(n).toLocaleString('pt-BR', { maximumFractionDigits: digits });
const date = (v) => v ? new Date(v.slice(0, 10) + 'T12:00:00').toLocaleDateString('pt-BR') : 'Sem registro';
const daysBefore = (v, n) => { const d = new Date(v + 'T12:00:00Z'); d.setUTCDate(d.getUTCDate() - n); return d.toISOString().slice(0, 10); };
const kinds = { running: 'Corrida', strength: 'Força', cycling: 'Bike', swimming: 'Natação', other: 'Outros' };
const colors = { fitness: '#3fb950', fatigue: '#f78166', form: '#d29922', volume: '#3fb950', km: '#3fb950' };
const nav = [['dashboard','Dashboard'],['workouts','Workouts'],['nutrition','Nutrition'],['sleep','Sleep']];
const sections = {
  workouts:[['overview','Visão geral'],['running','Corrida'],['strength','Força']],
};
const groupFor = tab => Object.keys(sections).find(group=>sections[group].some(([id])=>id===tab)) || tab;
const tabLabel = tab => [...nav,...Object.values(sections).flat()].find(([id])=>id===tab)?.[1] || 'Hoje';
async function api(path, body) {
  const response = await fetch('/api/' + path, { credentials: 'same-origin', cache: 'no-store', ...(body ? { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-AscentIQ-Request': '1' }, body: JSON.stringify(body) } : {}) });
  if (!response.ok) { const payload = await response.json().catch(() => ({})); const error = new Error(payload.detail || (response.status === 401 ? 'Entre novamente para acessar seus dados.' : 'Não foi possível concluir a solicitação.')); error.status = response.status; throw error; }
  return response.json();
}
function Peak({ small = false }) { return <svg viewBox="0 0 48 44" width={small ? 27 : 43} fill="none" aria-hidden="true"><path d="M3 38 21 5l9 17 5-9 10 25H3Z" stroke="currentColor" strokeWidth="2.3"/><path d="m14 19 7 5 7-6M8 38l13-14 13 14" stroke="currentColor" strokeWidth="1.5"/></svg>; }
function Card({ label, value, unit, note, tone = '' }) { return <div className={'metric ' + tone}><div className="eyebrow">{label}</div><div className="metric-value">{value}<span>{unit}</span></div><div className="muted small">{note}</div></div>; }
function Panel({ title, sub, children, aside, className = '' }) { return <section className={'panel ' + className}><div className="panel-heading"><div><h2>{title}</h2>{sub && <p>{sub}</p>}</div>{aside}</div>{children}</section>; }
function Empty({ children = 'Nenhum registro nesse período.' }) { return <div className="empty">{children}</div>; }

function Chart({ rows, keys: inputKeys, height = 290, numbers = false, points = false, zeroBaseline = !inputKeys.some(k => ['weight_kg', 'waist_cm'].includes(k.key)), title = 'Evolução dos dados' }) {
  const keys = inputKeys.map(k => ({...k, color: ({'#16695e':'#3fb950','#bd633e':'#f78166','#a88926':'#d29922'})[k.color] || k.color || colors[k.key]}));
  const [hover, setHover] = useState(null);
  if (!rows.length || !keys.some(k => rows.some(r => r[k.key] != null))) return <Empty/>;
  const w = 1000, h = height, left = 45, right = 18, top = 22, bottom = 38;
  const values = rows.flatMap(r => keys.map(k => r[k.key]).filter(v => v != null).map(Number));
  const rawMin = Math.min(...values), rawMax = Math.max(...values);
  const padding = zeroBaseline ? 0 : Math.max((rawMax-rawMin)*.15, Math.abs(rawMax)*.002, .05);
  const min = zeroBaseline ? Math.min(0,rawMin) : rawMin-padding;
  const max = zeroBaseline ? Math.max(1,rawMax) : rawMax+padding;
  const span = max - min || 1;
  const timestamps = rows.map(row => Date.parse(row.date));
  const firstDate = Math.min(...timestamps), dateSpan = Math.max(...timestamps)-firstDate;
  const x = (i) => left + (dateSpan ? (timestamps[i]-firstDate)/dateSpan : .5) * (w-left-right);
  const y = (v) => h - bottom - (v - min) / span * (h - top - bottom);
  const select = (event) => { const b = event.currentTarget.getBoundingClientRect(); const px = (event.clientX - b.left) / b.width * w; let nearest = 0; rows.forEach((_,i)=>{if(Math.abs(x(i)-px)<Math.abs(x(nearest)-px))nearest=i;});setHover(nearest); };
  return <div className="chart"><div className="legend">{keys.map(k => <span key={k.key}><i style={{ background: k.color || colors[k.key] }}/>{k.label}</span>)}</div><svg role="img" aria-label={title} viewBox={`0 0 ${w} ${h}`} onPointerMove={select} onPointerLeave={() => setHover(null)}>
    {Array.from({ length: 5 }, (_, i) => { const value = min + span * i / 4; return <g key={i}><line x1={left} x2={w-right} y1={y(value)} y2={y(value)} stroke="#e5e4dc" strokeDasharray="4 5"/><text x="3" y={y(value)+4} className="chart-label">{fmt(value, span < 5 ? 2 : span < 20 ? 1 : 0)}</text></g>; })}
    {keys.map(k => { const chunks = []; let current = []; rows.forEach((r, i) => { if (r[k.key] != null) current.push([i,r[k.key]]); else if (current.length) { chunks.push(current); current=[]; } }); if(current.length) chunks.push(current); return <g key={k.key}>{chunks.map((chunk, i) => <polyline key={i} points={chunk.map(([idx,v]) => `${x(idx)},${y(v)}`).join(' ')} fill="none" stroke={k.color || colors[k.key]} strokeWidth="2.7" strokeLinejoin="round" strokeLinecap="round"/>)}{(points || rows.length <= 25) && rows.map((r,i) => r[k.key] != null && <g key={i}><circle cx={x(i)} cy={y(r[k.key])} r="3.4" fill={k.color || colors[k.key]}/>{numbers && <text x={x(i)} y={y(r[k.key])-9} textAnchor="middle" fill={k.color || colors[k.key]} fontSize="11">{fmt(r[k.key])}</text>}</g>)}</g>; })}
    {[...new Set([0, Math.floor((rows.length-1)/2), rows.length-1])].map((i,index) => <text key={i} x={x(i)} y={h-9} textAnchor={i===0?'start':i===rows.length-1?'end':'middle'} className="chart-label">{date(rows[i].date)}</text>)}
    {hover != null && <g><line x1={x(hover)} x2={x(hover)} y1={top} y2={h-bottom} stroke="#20372d" opacity=".25"/>{keys.map(k => rows[hover][k.key] != null && <circle key={k.key} cx={x(hover)} cy={y(rows[hover][k.key])} r="5" fill={k.color || colors[k.key]} stroke="#fff" strokeWidth="2"/>)}</g>}
  </svg><div className="chart-readout" aria-live="polite">{hover != null ? <><b>{date(rows[hover].date)}</b>{keys.map(k => <span key={k.key}>{k.label}: <strong>{fmt(rows[hover][k.key])}</strong></span>)}</> : 'Passe sobre o gráfico para consultar os valores por dia.'}</div></div>;
}
function Performance({ data }) {
  const [range,setRange] = useState(21), [numbers,setNumbers] = useState(false);
  const rows = data.performance.series.slice(-range);
  return <Panel title="Carga, adaptação e equilíbrio" sub="Seu modelo de Fitness, Fadiga e Forma. Uma leitura de carga, não um diagnóstico." aside={<div className="chart-controls"><select aria-label="Período do gráfico" value={range} onChange={e=>setRange(Number(e.target.value))}><option value={21}>3 semanas</option><option value={90}>90 dias</option><option value={180}>6 meses</option><option value={1500}>Todo o histórico</option></select><label className="check"><input type="checkbox" checked={numbers} onChange={e=>setNumbers(e.target.checked)}/>Valores</label></div>}><Chart rows={rows} keys={[{key:'fitness',label:'Fitness'},{key:'fatigue',label:'Fadiga'},{key:'form',label:'Forma'}]} numbers={numbers}/><details className="method"><summary>Como ler esses números</summary><p>Fitness = carga crônica suavizada em 42 dias. Fadiga = carga aguda em 7 dias. Forma = Fitness menos Fadiga. A carga combina FC, duração, modalidade, D+ e componente muscular Hevy. Não é TSS oficial, VO₂max nem percentual de condicionamento.</p><PagedList items={[...rows].reverse()} resetKey={range} label="carga diária">{page=><div className="table-scroll"><table><thead><tr><th>Data</th><th>Fitness</th><th>Fadiga</th><th>Forma</th><th>Carga</th></tr></thead><tbody>{page.map(r=><tr key={r.date}><td>{date(r.date)}</td><td>{fmt(r.fitness)}</td><td>{fmt(r.fatigue)}</td><td>{fmt(r.form)}</td><td>{fmt(r.daily_load)}</td></tr>)}</tbody></table></div>}</PagedList></details></Panel>;
}
function ActivityTable({rows,resetKey=''}) {
  return <PagedList items={rows} resetKey={resetKey} label="atividades" empty={<Empty/>}>{page=><div className="table-scroll"><table><thead><tr><th>Data / atividade</th><th>Modalidade</th><th>Distância</th><th>Tempo</th><th>FC média</th><th>D+</th></tr></thead><tbody>{page.map((r,i)=><tr key={r.id+'-'+i}><td><strong>{r.name}</strong><span className="small muted block">{date(r.date)}</span></td><td><span className={'tag '+r.kind}>{kinds[r.kind]}</span></td><td>{r.distance_km != null ? fmt(r.distance_km,2)+' km' : 'Sem dado'}</td><td>{r.elapsed_time || 'Sem dado'}</td><td>{r.avg_hr == null ? 'Sem dado' : r.avg_hr+' bpm'}</td><td>{r.elevation_gain_m == null ? 'Sem dado' : fmt(r.elevation_gain_m,0)+' m'}{r.elevation_source==='official'&&<span className="small block muted">Oficial</span>}</td></tr>)}</tbody></table></div>}</PagedList>;
}
function Filter({ from, to, setFrom, setTo, search, setSearch }) { return <div className="filters"><label>De<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Até<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><label className="search">Buscar<input type="search" value={search} placeholder="Nome da atividade ou exercício" onChange={e=>setSearch(e.target.value)}/></label></div>; }
function Overview({ data }) {
  const s=data.performance.summary, week=data.week, body=data.body.current || {};
  const goal=data.goals?.endurance;
  return <>

  {goal?.status==='active_goal'&&<section className="current-goal" aria-label="Objetivo esportivo atual"><span className="eyebrow">OBJETIVO ESPORTIVO ATUAL</span><strong>{goal.name} · {fmt(goal.target_distance_km,0)} km</strong><span>{date(goal.event_date)} · Objetivo: completar bem, com endurance e gestão de esforço. Pace não é meta.</span></section>}
  <div className="metrics three"><Card label="Fitness" value={fmt(s.fitness)} note="Carga crônica · 42 dias" tone="green"/><Card label="Fadiga" value={fmt(s.fatigue)} note="Carga aguda · 7 dias" tone="rust"/><Card label="Forma" value={(s.form>0?'+':'')+fmt(s.form)} note="Fitness − Fadiga · índice estimado" tone="gold"/></div><Performance data={data}/>
  <div className="split"><Panel title="Sua semana em movimento" sub={`${date(week.start)} a ${date(week.end)} · últimos 7 dias`}><div className="week-stats"><div><b>{fmt(week.running_km,2)}</b><span>km de corrida</span></div><div><b>{week.strength_sessions}</b><span>sessões de força</span></div><div><b>{week.working_sets}</b><span>séries de trabalho</span></div><div><b>{fmt(week.running_elevation_m,0)}</b><span>metros D+ corrida</span></div></div><div className="mix">{Object.entries(week.by_kind).map(([k,n])=><div key={k}><span>{kinds[k]}</span><div className="mix-bar"><i style={{width: (n/Math.max(1,week.activity_count)*100)+'%'}}/></div><b>{n}</b></div>)}</div></Panel><Panel title="Corpo & recuperação" sub="Referências com data, sem inferir medidas atuais"><div className="reference"><span>Avaliação corporal · {date(data.body.reference_date)}</span><b>{fmt(body.body_fat_pct,2)}<small>% gordura</small></b><div>{fmt(body.weight_kg)} kg · {fmt(body.lean_mass_kg,2)} kg de massa magra</div></div><SleepContext sleep={data.sleep}/></Panel></div>
  <Panel title="Atividades mais recentes" sub="Garmin para o esforço cardiovascular. Hevy para séries e exercícios."><ActivityTable rows={data.activities}/></Panel><div className="footnote">Base privada · {data.activities.length} atividades · {data.strength.length} sessões de força consolidadas · Sem LLM nos cálculos</div></>;
}
function Running({ data }) {
  const [from,setFrom]=useState(daysBefore(data.as_of,90)),[to,setTo]=useState(data.as_of),[search,setSearch]=useState(''); const query=useDeferredValue(search.toLowerCase());
  const rows=data.activities.filter(r=>r.kind==='running'&&r.date>=from&&r.date<=to&&r.name?.toLowerCase().includes(query));
  const total=rows.reduce((a,r)=>({km:a.km+(r.distance_km||0),seconds:a.seconds+(r.duration_seconds||0),d:a.d+(r.elevation_gain_m||0)}),{km:0,seconds:0,d:0});
  const weeks={}; rows.forEach(r=>{const d=new Date(r.date+'T12:00:00Z'); const offset=(d.getUTCDay()+6)%7; const key=daysBefore(r.date,offset); weeks[key]=(weeks[key]||0)+(r.distance_km||0);});
  const chart=Object.entries(weeks).sort().map(([date,km])=>({date,km}));
  const races=data.race_index.entries || [];
  return <><Filter {...{from,to,setFrom,setTo,search,setSearch}}/><div className="metrics three"><Card label="Distância no período" value={fmt(total.km,2)} unit="km" note={`${rows.length} atividades`}/><Card label="Tempo em atividade" value={fmt(total.seconds/3600)} unit="h" note="Duração total registrada"/><Card label="Subida acumulada" value={fmt(total.d,0)} unit="m" note="GPX oficial quando vinculado; relógio nos demais"/></div><Panel title="Volume semanal de corrida" sub="Distância registrada por semana; semanas sem registros não são interpoladas."><Chart rows={chart} keys={[{key:'km',label:'km / semana'}]}/></Panel><Panel title="Histórico de corridas"><ActivityTable rows={rows} resetKey={from+to+query}/></Panel>{races.length>0 && <Panel title="Execução nas provas / IEP-100" sub={`Benchmark histórico, não prontidão atual. Índice calculado em ${date(data.race_index.generated_at)}.`}><Chart rows={races} keys={[{key:'performance_execution_index',label:'IEP / 100',color:'#a88926'}]} numbers/><PagedList items={races} label="provas">{page=><div className="table-scroll"><table><thead><tr><th>Prova</th><th>Data</th><th>Tempo</th><th>IEP</th><th>Confiança</th></tr></thead><tbody>{page.map((r,i)=><tr key={i}><td>{r.name}</td><td>{date(r.date)}</td><td>{r.elapsed_time}</td><td>{fmt(r.performance_execution_index)}</td><td>{r.confidence}</td></tr>)}</tbody></table></div>}</PagedList></Panel>}</>;
}
function Strength({ data }) {
  const [from,setFrom]=useState(daysBefore(data.as_of,90)),[to,setTo]=useState(data.as_of),[search,setSearch]=useState(''); const query=useDeferredValue(search.toLowerCase());
  const rows=data.strength.filter(r=>r.date>=from&&r.date<=to&&(`${r.title} ${r.exercises.map(x=>x.name).join(' ')}`).toLowerCase().includes(query));
  const group=(name)=>{const n=name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase(); if(/abdominal|prancha|rotac|flexao lateral|joelhos nas barras/.test(n))return null; if(/agachamento|abdutor|adutor|extensora|flexora|panturrilha|quadril|pelvic|perna|leg press|terra|impulso/.test(n))return 'legs'; if(/ombro|desenvolvimento|shoulder|encolhimento|triceps|biceps|rosca|supino|crucifixo|voador|puxada|remada|barra fixa|fundos sentado|punho/.test(n))return 'upper'; return null;};
  const weeks={}; rows.forEach(r=>{const key=daysBefore(r.date,(new Date(r.date+'T12:00:00Z').getUTCDay()+6)%7); const bucket=weeks[key] ||= {date:key,legs:0,upper:0}; r.exercises.forEach(e=>{const kind=group(e.name); if(kind)bucket[kind]+=e.sets.reduce((sum,s)=>sum+(s.set_type==='normal'&&Number(s.weight_kg)>0&&Number(s.reps)>0?Number(s.weight_kg)*Number(s.reps):0),0);});});
  const volumeSeries=Object.values(weeks).sort((a,b)=>a.date.localeCompare(b.date)).map(r=>({...r,legs:Math.round(r.legs),upper:Math.round(r.upper)}));
  const sum=k=>rows.reduce((a,r)=>a+(r[k]||0),0);
  return <><Filter {...{from,to,setFrom,setTo,search,setSearch}}/><div className="metrics three"><Card label="Sessões de força" value={rows.length} note="Cada sessão consolidada conta uma vez"/><Card label="Séries de trabalho" value={sum('working_sets')} note="Aquecimentos excluídos quando identificados"/><Card label="Volume registrado" value={fmt(sum('volume_kg'),0)} unit="kg·rep" note="Total Hevy; inclui exercícios fora do gráfico"/></div><Panel title="Volume semanal de força" sub="Carga × repetições nas séries de trabalho, separada por grupo. Core, séries sem carga e sessões sem detalhe Hevy não entram nas linhas."><Chart rows={volumeSeries} keys={[{key:'legs',label:'Pernas / kg·rep',color:'#3fb950'},{key:'upper',label:'Superiores / kg·rep',color:'#f78166'}]} title="Volume semanal de pernas e superiores"/></Panel><Panel title="Diário de musculação" sub={`${rows.length} sessões no período · detalhes completos por exercício`}><PagedList items={rows} resetKey={from+to+query} label="sessões de força" empty={<Empty/>}>{page=>page.map((r,i)=><details className="session" key={r.id+'-'+i}><summary><div><strong>{r.title}</strong><span>{date(r.date)} · {r.duration || 'Sem duração'} · {r.avg_hr != null ? `${r.avg_hr} bpm média · ` : ''}{r.max_hr != null ? `${r.max_hr} bpm máx · ` : ''}{r.match_status==='matched' ? 'Garmin + Hevy' : r.exercises.length ? 'Hevy' : 'Garmin / sem séries'}</span></div><div className="session-stats">{fmt(r.volume_kg,0)} <small>kg·rep</small><b>{r.working_sets == null ? 'Sem dado' : r.working_sets+' séries'}</b></div></summary><PagedList items={r.exercises} label="exercícios" empty={<Empty>Esta sessão tem contexto Garmin, mas não há séries correspondentes do Hevy.</Empty>}>{exercises=>exercises.map((e,j)=><div className="exercise" key={j}><h3>{e.name}</h3><PagedList items={e.sets.map((s,k)=>({...s,number:k+1}))} label="séries">{sets=><div className="table-scroll"><table><thead><tr><th>Série</th><th>Tipo</th><th>Carga / kg</th><th>Repetições</th></tr></thead><tbody>{sets.map(s=><tr key={s.number}><td>{s.number}</td><td>{s.set_type==='warmup'?'Aquecimento':s.set_type==='normal'?'Trabalho':s.set_type}</td><td>{fmt(s.weight_kg)}</td><td>{s.reps ?? 'Sem dado'}</td></tr>)}</tbody></table></div>}</PagedList></div>)}</PagedList></details>)}</PagedList></Panel></>;
}
const bodyLabels={chest:'Tórax',right_arm:'Braço direito',left_arm:'Braço esquerdo',right_forearm:'Antebraço direito',left_forearm:'Antebraço esquerdo',right_wrist:'Punho direito',left_wrist:'Punho esquerdo',abdomen:'Abdômen',waist:'Cintura',hip:'Quadril',right_thigh:'Coxa direita',left_thigh:'Coxa esquerda',right_calf:'Panturrilha direita',left_calf:'Panturrilha esquerda',axillary:'Axilar',triceps:'Tríceps',subscapular:'Subescapular',abdominal:'Abdominal',suprailiac:'Suprailíaca',thigh:'Coxa',total:'Soma'};
function Body({ data }) { const b=data.body.current||{}, history=data.body.history||[], target=data.nutrition.initial_nutrition_target||{}; return <><PageTitle kicker="COMPOSIÇÃO / MEDIDAS / REFERÊNCIAS" title="O corpo também tem história." text={`Última avaliação: ${date(data.body.reference_date)}. Sem extrapolar medidas para hoje.`}/><div className="metrics four"><Card label="Peso medido" value={fmt(b.weight_kg)} unit="kg" note={date(data.body.reference_date)}/><Card label="Gordura corporal" value={fmt(b.body_fat_pct,2)} unit="%" note="Avaliação antropométrica"/><Card label="Massa magra" value={fmt(b.lean_mass_kg,2)} unit="kg" note="Referência de preservação"/><Card label="Cintura" value={fmt(b.waist_cm)} unit="cm" note="Não confundir com medida abdominal"/></div><div className="split"><Panel title="Peso ao longo do tempo" sub="Somente pontos medidos"><Chart rows={history} keys={[{key:'weight_kg',label:'Peso / kg',color:'#16695e'}]} numbers height={220}/></Panel><Panel title="Cintura ao longo do tempo" sub="Verificar consistência do protocolo de medição"><Chart rows={history} keys={[{key:'waist_cm',label:'Cintura / cm',color:'#bd633e'}]} numbers height={220}/></Panel></div><div className="split"><Panel title="Perimetria" sub={`Centímetros · avaliação de ${date(data.body.reference_date)}`}><div className="measure-grid">{Object.entries(data.body.perimetry_current_cm||{}).map(([k,v])=><div key={k}><span>{bodyLabels[k]||k}</span><b>{fmt(v)} <small>cm</small></b></div>)}</div></Panel><Panel title="Dobras cutâneas" sub="Milímetros · valores medidos no mesmo protocolo"><div className="measure-grid">{Object.entries(data.body.skinfolds_current_mm||{}).map(([k,v])=><div key={k}><span>{bodyLabels[k]||k}</span><b>{fmt(v)} <small>mm</small></b></div>)}</div></Panel></div><Panel title="Nutrição de referência" sub={`Alvos previamente registrados em ${date(data.nutrition.generated_at)}. Não é uma nova prescrição.`}><div className="week-stats"><div><b>{fmt(target.average_kcal_day,0)}</b><span>kcal / dia</span></div><div><b>{target.protein_g_day ?? 'Sem dado'} g</b><span>proteína</span></div><div><b>{target.carbohydrate_g_day ?? 'Sem dado'} g</b><span>carboidrato</span></div><div><b>{target.fat_g_day ?? 'Sem dado'} g</b><span>gordura</span></div></div><p className="muted">{data.body.active_goal?.notes}</p></Panel></>; }
function Medical({ data }) { const m=data.medical; const [query,setQuery]=useState(''); const search=useDeferredValue(query.toLowerCase()); const clearance=m.status.sports_clearance||{}; return <><PageTitle kicker="SAÚDE / DOCUMENTOS / CONTEXTO" title="Exames, sem perder o contexto." text={m.disclaimer}/><div className="medical-intro"><div><span className="eyebrow">ATESTADO REGISTRADO</span><h2>{clearance.status==='cleared'?'Aptidão física documentada':'Sem atestado registrado'}</h2><p>{date(clearance.date)} · {clearance.scope}</p></div><span className="tag">Arquivo médico privado</span></div><Panel title="Resumo já registrado" sub={`Base médica atualizada em ${date(m.updated_at)}`}><p>{m.status.cardiovascular_summary}</p><div className="notice"><b>Contexto da coleta · {date(m.context.laboratory_collection_date)}</b><p>{m.context.athlete_report}</p><p className="small">{m.context.interpretive_relevance}</p></div>{m.status.active_follow_up?.length>0 && <><h3>Acompanhamentos anotados na base</h3><ul>{m.status.active_follow_up.map((x,i)=><li key={i}>{x}</li>)}</ul></>}</Panel><Panel title="Documentos e resultados" sub="Conclusões e observações abaixo são as já armazenadas, não uma nova avaliação médica."><label className="search block">Buscar exame ou indicador<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ex.: glicose, TSH, HDL, Holter"/></label>{m.records.filter(r=>(r.label+' '+r.rows.map(x=>x.label+' '+x.value).join(' ')).toLowerCase().includes(search)).map((r,i)=><details className="session medical-record" key={i} open={search ? true : undefined}><summary><div><strong>{r.label}</strong><span>{date(r.date)} · {r.rows.length} resultados e observações</span></div><span className="tag">Consultar</span></summary><div className="document-links">{r.documents.map(d=><a key={d.id} href={'/api/medical/documents/'+d.id} target="_blank" rel="noreferrer">Documento original ↗</a>)}</div><div className="table-scroll"><table><thead><tr><th>Indicador / contexto</th><th>Resultado registrado</th></tr></thead><tbody>{r.rows.filter(x=>!search || (x.label+' '+x.value).toLowerCase().includes(search) || r.label.toLowerCase().includes(search)).map((x,j)=><tr key={j}><td>{x.label}</td><td>{x.value}</td></tr>)}</tbody></table></div>{Object.entries(r.trends||{}).map(([key,rows])=><Panel key={key} title={key.replaceAll('_',' ')} sub="Histórico transcrito do laudo"><Chart rows={rows} keys={[{key:'value',label:'Resultado',color:'#16695e'}]} height={210} numbers/></Panel>)}</details>)}</Panel>{data.physiology.map((test,i)=><Panel key={i} title="Teste de esforço / referência fisiológica" sub="Valores disponíveis na extração do documento"><p>FC de pico no teste: <strong>{test.peak_hr_bpm} bpm</strong>. Isso não substitui a FC máxima adotada no modelo.</p><div className="notice">{test.notes?.map((n,j)=><p key={j}>{n}</p>)}</div></Panel>)}</>; }
function PageTitle({ kicker,title,text }) { return <div className="page-title"><div className="eyebrow">{kicker}</div><h1>{title}</h1><p>{text}</p></div>; }
function ReportLinks({ report }) { return report ? <div className="report-links"><a className="button" href={'/api/reports/'+report.id+'/html'} target="_blank" rel="noreferrer">Dashboard Typst HTML ↗</a><a className="button download" href={'/api/reports/'+report.id+'/pdf'} download>Baixar PDF</a></div> : null; }
function Reports({ reports,jobs,onJob,busy }) { return <><PageTitle kicker="AUTOMAÇÃO / TYPST / RASTREABILIDADE" title="Uma fotografia de cada semana." text="Relatórios reproduzíveis, com a versão do modelo e a data de cada fonte."/><Panel title="Geração de relatórios" sub={jobs.schedule}><div className="report-actions"><button className="primary" disabled={busy} onClick={()=>onJob('sync')}>Atualizar treinos e gerar</button><button disabled={busy} onClick={()=>onJob('generate')}>Gerar com a base atual</button></div><p className="small muted">O agendamento roda enquanto o Docker estiver ligado. Apenas uma atualização é executada por vez.</p></Panel><Panel title="Histórico de execução">{jobs.jobs?.length ? <div className="table-scroll"><table><thead><tr><th>Início</th><th>Modo</th><th>Estado</th><th>Etapa / resultado</th></tr></thead><tbody>{jobs.jobs.map(j=><tr key={j.id}><td>{new Date(j.created_at).toLocaleString('pt-BR')}</td><td>{j.mode==='sync'?'Atualização + PDF':'Base atual + PDF'}</td><td><span className={'tag '+j.status}>{({queued:'Na fila',running:'Em execução',completed:'Concluído',partial:'Parcial',failed:'Falhou'})[j.status]}</span></td><td>{j.message}{JSON.parse(j.warnings||'[]').map((w,i)=><p key={i} className="small">{w}</p>)}</td></tr>)}</tbody></table></div>:<Empty/>}</Panel><Panel title="Arquivo de relatórios" sub="PDFs gerados localmente com Typst, sem enviar dados ao typst.app">{reports.length?reports.map(r=><div className="report-row" key={r.id}><div><strong>Relatório · {date(r.as_of)}</strong><span className="muted small block">{new Date(r.generated_at).toLocaleString('pt-BR')} · {r.model_version}{r.warnings?.length?' · Fontes parciais':''}</span></div><a className="button" href={'/api/reports/'+r.id+'/pdf'} target="_blank" rel="noreferrer">Abrir PDF ↗</a></div>):<Empty>O primeiro relatório está sendo preparado.</Empty>}</Panel></>; }
function Login({ onLogin }) { const [username,setUsername]=useState('alvaro'),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false); async function submit(e){e.preventDefault();setBusy(true);setError('');try{await api('auth/login',{username,password});setPassword('');onLogin();}catch(e){setError(e.message);}finally{setBusy(false);}} return <div className="login-page"><div className="login-story"><div className="brand"><Peak/><span>AscentIQ<small>ATHLETE INTELLIGENCE</small></span></div><h1>Seu histórico.<br/>Sua evolução.<br/><em>Seu próximo cume.</em></h1><p>Treino, performance e saúde.<br/>Uma base privada. Uma visão completa.</p><div className="login-line">GARMIN + HEVY + DADOS DO ATLETA</div></div><form className="login-card" onSubmit={submit}><div className="eyebrow">ACESSO PRIVADO</div><h2>Entre no seu painel.</h2><p>Os dados de treino e saúde ficam no seu próprio ambiente.</p><label>Usuário<input autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} required/></label><label>Senha<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<div className="error" role="alert">{error}</div>}<button className="primary" disabled={busy}>{busy?'Entrando…':'Acessar dashboard'}</button><div className="small muted">Primeiro acesso: credenciais no arquivo local <code>runtime/dashboard/access.txt</code>.</div></form></div>; }
function NavIcon({id}) {
  const paths={dashboard:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',workouts:'M3 8v8 M6 5v14 M18 5v14 M21 8v8 M6 12h12',nutrition:'M6 3v8 M3 3v5a3 3 0 0 0 6 0V3 M6 11v10 M18 3c-5 4-5 9 0 9 M18 3v18',sleep:'M20 15.5A8.5 8.5 0 0 1 8.5 4 8.5 8.5 0 1 0 20 15.5'};
  return <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[id]}/></svg>;
}
function AccountMenu({name,onNavigate,onLogout}) {
  const ref=React.useRef(null);
  useEffect(()=>{
    const close=e=>{if(!ref.current?.contains(e.target))ref.current.open=false;};
    const escape=e=>{if(e.key==='Escape'&&ref.current?.open){ref.current.open=false;ref.current.querySelector('summary').focus();}};
    document.addEventListener('pointerdown',close);document.addEventListener('keydown',escape);
    return()=>{document.removeEventListener('pointerdown',close);document.removeEventListener('keydown',escape);};
  },[]);
  function select(action){ref.current.open=false;action();}
  return <details ref={ref} className="account-menu"><summary aria-label="Abrir menu da conta"><span className="avatar">{(name || 'Você').split(' ').slice(0,2).map(x=>x[0]).join('')}</span><span className="account-name">{name || 'Minha conta'}</span><span aria-hidden="true">⌄</span></summary><div className="account-dropdown"><strong>{name || 'Minha conta'}</strong><button onClick={()=>select(()=>onNavigate('profile'))}>Conta e perfil</button><button onClick={()=>select(()=>onNavigate('settings'))}>Dados e fontes</button><button onClick={()=>select(onLogout)}>Sair</button></div></details>;
}
function App() {
  const [authenticated,setAuthenticated]=useState(null),[data,setData]=useState(null),[tab,setTab]=useState('dashboard'),[jobs,setJobs]=useState({jobs:[]}),[error,setError]=useState('');
  const [modal,setModal]=useState(null),[modalState,setModalState]=useState({busy:false,dirty:false}),[mobileMenu,setMobileMenu]=useState(false);
  const [assistantOpen,setAssistantOpen]=useState(false),[assistantMinimized,setAssistantMinimized]=useState(false),[assistantStarted,setAssistantStarted]=useState(false);
  const [contextDay,setContextDay]=useState(today);
  const busy=jobs.jobs.some(j=>['queued','running'].includes(j.status));
  async function refresh(){try{const [d,j]=await Promise.all([api('dashboard'),api('jobs')]);setData(d);setJobs(j);setError('');}catch(e){if(e.status===401){setAuthenticated(false);setData(null);}else setError(e.message);}}
  useEffect(()=>{api('auth/session').then(()=>setAuthenticated(true)).catch(()=>setAuthenticated(false));if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});},[]);
  useEffect(()=>{const expired=()=>{setAuthenticated(false);setData(null);};window.addEventListener('ascentiq-session-expired',expired);return()=>window.removeEventListener('ascentiq-session-expired',expired);},[]);
  useEffect(()=>{if(!authenticated)return;refresh();const timer=setInterval(refresh,5000);return()=>clearInterval(timer);},[authenticated]);
  async function onJob(mode){try{await api('jobs',{mode});await refresh();}catch(e){setError(e.message);}}
  async function logout(){try{await api('auth/logout',{});setAuthenticated(false);setData(null);setAssistantStarted(false);setModal(null);}catch(e){setError(e.message);}}
  function openAssistant(day){if(typeof day==='string')setContextDay(day);setAssistantStarted(true);setAssistantOpen(true);setAssistantMinimized(false);}
  function navigate(id,day){if(modal&&id!==modal&&(modalState.busy || (modalState.dirty&&!window.confirm('Descartar as alterações ainda não salvas?'))))return;if(typeof day==='string')setContextDay(day);setMobileMenu(false);if(id==='assistant'){openAssistant(day);return;}if(['goals','profile','settings','documents'].includes(id)){setModalState({busy:false,dirty:false});setModal(id);return;}setTab(id==='today'?'dashboard':id==='workouts'?'overview':id);window.scrollTo({top:0,behavior:'smooth'});}
  if(authenticated===null)return <div className="loading">Carregando AscentIQ…</div>;
  if(!authenticated)return <Login onLogin={()=>setAuthenticated(true)}/>;
  if(!data)return <div className="loading">{error || 'Preparando seu histórico…'}{error&&<button onClick={refresh}>Tentar novamente</button>}</div>;
  const active=jobs.jobs.find(j=>['queued','running'].includes(j.status));
  return <div className="app"><header className="topbar"><div><button className="mobile-menu-button" aria-label="Abrir menu principal" aria-expanded={mobileMenu} onClick={()=>setMobileMenu(v=>!v)}>☰</button><div className="brand"><Peak/><span>AscentIQ<small>SAÚDE E FITNESS PESSOAL</small></span></div></div><div className="topbar-right"><span className="sync-date"><i/>{busy?'Atualização em andamento':`Treinos: ${date(data.freshness.activities)}`}</span><AccountMenu name={data.athlete.name} onNavigate={navigate} onLogout={logout}/></div></header>
    {mobileMenu&&<button className="menu-backdrop" aria-label="Fechar menu" onClick={()=>setMobileMenu(false)}/>}
    <aside className={'sidebar '+(mobileMenu?'mobile-open':'')}>

      <div className="sidebar-label">SEU PAINEL</div>
      <nav aria-label="Áreas do painel">{nav.map(([id,label])=><button key={id} className={groupFor(tab)===id?'active':''} aria-current={groupFor(tab)===id?'page':undefined} onClick={()=>navigate(id)}><NavIcon id={id}/><span>{label}</span></button>)}</nav>

    </aside>
    <main>

      <div className="content">
        {sections[groupFor(tab)]&&<nav className="section-tabs" aria-label={'Áreas de '+tabLabel(groupFor(tab))}>{sections[groupFor(tab)].map(([id,label])=><button key={id} className={tab===id?'active':''} aria-current={tab===id?'page':undefined} onClick={()=>setTab(id)}>{label}</button>)}{tab==='overview'&&<button className="primary training-analysis-action" onClick={()=>{setModalState({busy:false,dirty:false});setModal('training-analysis');}}>Analisar treinos do dia</button>}</nav>}
        {error&&<div className="error" role="alert">{error}<button onClick={()=>setError('')}>Fechar</button></div>}
        {active&&<div className="job-banner" role="status"><span className="spinner"/>{active.message}. Você pode continuar consultando a última versão.</div>}
        {data.sync_warnings?.length>0&&<div className="notice">Atualização parcial: {data.sync_warnings.join(' ')}</div>}
        {tab==='dashboard'&&<Today data={data} onNavigate={navigate} onAssistant={openAssistant}/>}
        {tab==='overview'&&<Overview data={data}/>}
        {tab==='running'&&<Running data={data}/>}
        {tab==='strength'&&<Strength data={data}/>}
        {tab==='sleep'&&<Sleep data={data} Chart={Chart} Card={Card} Panel={Panel}/>}
        {tab==='nutrition'&&<Nutrition initialDay={contextDay}/>}
        <footer>ASCENTIQ <span>Fonte de verdade: seus registros. Cálculos locais. Dados de saúde privados.</span><span>{data.storage?.backend==='postgres'?'PostgreSQL local · ':''}Snapshot: {new Date(data.generated_at).toLocaleString('pt-BR')}</span></footer>
      </div>
    </main>
    {modal&&<Modal title={({goals:'Objetivos e plano',profile:'Perfil e medidas',settings:'Dados e fontes',documents:'Documentos privados','training-analysis':'Análise dos treinos'})[modal]} className="modal-wide" busy={modalState.busy} dirty={modalState.dirty} onClose={()=>{setModal(null);refresh();}}>{modal==='goals'&&<Goals initialDay={contextDay} onStateChange={setModalState}/>} {modal==='profile'&&<Health Chart={Chart} initialDay={contextDay} onStateChange={setModalState}/>} {modal==='settings'&&<><div className="report-actions"><button onClick={()=>navigate('documents')}>Documentos privados</button></div><Settings onJob={onJob} busy={busy} onStateChange={setModalState}/></>} {modal==='documents'&&<Documents onStateChange={setModalState}/>} {modal==='training-analysis'&&<DailyAnalysis data={data} onStateChange={setModalState}/>}</Modal>}
    {assistantStarted&&<section className="assistant-dock" aria-label="Assistente pessoal" hidden={!assistantOpen || assistantMinimized}><header className="assistant-dock-heading"><div><strong>Seu assistente</strong><span>Converse com seus registros</span></div><div><button className="icon-button" aria-label="Minimizar assistente" onClick={()=>setAssistantMinimized(true)}>−</button><button className="icon-button" aria-label="Fechar assistente" onClick={()=>setAssistantOpen(false)}>✕</button></div></header><div className="assistant-dock-body"><Assistant compact day={contextDay}/></div></section>}
    {assistantOpen&&assistantMinimized&&<button className="assistant-restore" onClick={()=>setAssistantMinimized(false)}>Abrir assistente</button>}
  </div>;
}
createRoot(document.getElementById('root')).render(<><App/><InstallApp/></>);
