CREATE SCHEMA IF NOT EXISTS athlete;
CREATE SCHEMA IF NOT EXISTS operations;
CREATE TABLE IF NOT EXISTS athlete.schema_migrations(version text PRIMARY KEY, checksum text NOT NULL, applied_at timestamptz DEFAULT now());
CREATE TABLE athlete.revisions(id uuid PRIMARY KEY, athlete_id uuid NOT NULL, digest text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), reason text NOT NULL, warnings jsonb NOT NULL DEFAULT '[]', UNIQUE(athlete_id,digest));
CREATE TABLE athlete.state(singleton boolean PRIMARY KEY DEFAULT true CHECK(singleton), active_revision uuid REFERENCES athlete.revisions(id));
INSERT INTO athlete.state(singleton) VALUES(true);
CREATE TABLE athlete.dataset_blobs(digest text PRIMARY KEY, payload jsonb NOT NULL, original_bytes bytea NOT NULL);
CREATE TABLE athlete.datasets(revision_id uuid REFERENCES athlete.revisions(id), path text NOT NULL, digest text REFERENCES athlete.dataset_blobs(digest), PRIMARY KEY(revision_id,path));
CREATE TABLE athlete.profiles(revision_id uuid PRIMARY KEY REFERENCES athlete.revisions(id), athlete_id uuid NOT NULL, profile jsonb NOT NULL, preferences jsonb NOT NULL, goals jsonb NOT NULL);
CREATE TABLE athlete.activities(revision_id uuid REFERENCES athlete.revisions(id), id uuid NOT NULL, activity_date date, started_at_original text, kind text, name text, distance_km double precision, duration_seconds double precision, avg_hr double precision, max_hr double precision, watch_gain_m double precision, official_gain_m double precision, payload jsonb NOT NULL, PRIMARY KEY(revision_id,id));
CREATE INDEX activities_date ON athlete.activities(revision_id,activity_date);
CREATE TABLE athlete.activity_sources(revision_id uuid NOT NULL, activity_id uuid NOT NULL, provider text NOT NULL, external_id text NOT NULL, payload jsonb NOT NULL, PRIMARY KEY(revision_id,provider,external_id), FOREIGN KEY(revision_id,activity_id) REFERENCES athlete.activities(revision_id,id));
CREATE TABLE athlete.races(revision_id uuid REFERENCES athlete.revisions(id), ordinal integer, activity_id uuid, payload jsonb NOT NULL, PRIMARY KEY(revision_id,ordinal), FOREIGN KEY(revision_id,activity_id) REFERENCES athlete.activities(revision_id,id));
CREATE TABLE athlete.strength_sessions(revision_id uuid NOT NULL REFERENCES athlete.revisions(id), id uuid NOT NULL, activity_id uuid, activity_date date, match_status text, title text, total_sets integer, working_sets integer, reps integer, volume_kg double precision, payload jsonb NOT NULL, PRIMARY KEY(revision_id,id), FOREIGN KEY(revision_id,activity_id) REFERENCES athlete.activities(revision_id,id));
CREATE TABLE athlete.exercises(revision_id uuid, session_id uuid, ordinal integer, name text, payload jsonb NOT NULL, PRIMARY KEY(revision_id,session_id,ordinal), FOREIGN KEY(revision_id,session_id) REFERENCES athlete.strength_sessions(revision_id,id));
CREATE TABLE athlete.exercise_sets(revision_id uuid, session_id uuid, exercise_ordinal integer, ordinal integer, set_type text, weight_kg double precision, reps integer, rpe double precision, payload jsonb NOT NULL, PRIMARY KEY(revision_id,session_id,exercise_ordinal,ordinal), FOREIGN KEY(revision_id,session_id,exercise_ordinal) REFERENCES athlete.exercises(revision_id,session_id,ordinal));
CREATE TABLE athlete.body_measurements(revision_id uuid REFERENCES athlete.revisions(id), ordinal integer, measured_on date, weight_kg double precision, waist_cm double precision, body_fat_pct double precision, lean_mass_kg double precision, payload jsonb NOT NULL, PRIMARY KEY(revision_id,ordinal));
CREATE TABLE athlete.medical_records(revision_id uuid REFERENCES athlete.revisions(id), ordinal integer, recorded_on date, kind text, label text, payload jsonb NOT NULL, PRIMARY KEY(revision_id,ordinal));
CREATE TABLE athlete.medical_observations(revision_id uuid, record_ordinal integer, code text, result jsonb NOT NULL, PRIMARY KEY(revision_id,record_ordinal,code), FOREIGN KEY(revision_id,record_ordinal) REFERENCES athlete.medical_records(revision_id,ordinal));
CREATE TABLE athlete.sleep_records(revision_id uuid REFERENCES athlete.revisions(id), dataset text, ordinal integer, recorded_on_original text, payload jsonb NOT NULL, PRIMARY KEY(revision_id,dataset,ordinal));
CREATE TABLE athlete.daily_metrics(revision_id uuid REFERENCES athlete.revisions(id), metric_date date, model_version text NOT NULL, daily_load double precision, fitness double precision, fatigue double precision, form double precision, payload jsonb NOT NULL, PRIMARY KEY(revision_id,metric_date));
CREATE TABLE athlete.documents(revision_id uuid REFERENCES athlete.revisions(id), path text, sha256 text, bytes bigint NOT NULL, PRIMARY KEY(revision_id,path));
CREATE TABLE athlete.reports(id text PRIMARY KEY, revision_id uuid REFERENCES athlete.revisions(id), metadata jsonb NOT NULL, created_at timestamptz DEFAULT now());
CREATE TABLE operations.jobs(id text PRIMARY KEY, mode text, status text, created_at text, finished_at text, message text, warnings text, schedule_key text UNIQUE);
CREATE TABLE operations.settings(key text PRIMARY KEY, value text);
CREATE TABLE operations.sessions(digest text PRIMARY KEY, expires double precision);
CREATE INDEX jobs_status ON operations.jobs(status,created_at);
